Header
runbotics/runbotics pull request #103
Opened 2022-12-21 08:01 UTC by Klau-Sam

## Description
Create header for RB landing page

Screenshots:

![image](https://user-images.githubusercontent.com/63171496/208851365-95be7ca8-78f1-4574-9096-6f0def39d500.png)

![image](https://user-images.githubusercontent.com/63171496/208851514-cdf57aa4-7e89-4356-b55b-23f5ffab954c.png)

![image](https://user-images.githubusercontent.com/63171496/208851600-934772db-8684-4762-b3f9-ea3ea0a1825c.png)

![image](https://user-images.githubusercontent.com/63171496/208851676-1214d587-941b-49ce-a224-f9740380a397.png)

![image](https://user-images.githubusercontent.com/63171496/208851712-ae76fd24-6b5b-43f6-b871-24cfb7c5b658.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2022-12-21 12:02 UTC, preludium requested changes

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +  backdrop-filter: blur(0.5rem);
imo rem is not recommended here. We want to have constant behaviour but if the user's font size is changed the blur will be stronger

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +  z-index: 999;
move this value to global variables, we want to have full controller over the z-indexes

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +  display: flex;
display should be places above `justify-content` and `align-items` because those 2 depend on it

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +  margin-right: -$margin-1;
What's the purpose of a negative margin?

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +  display: flex;
adjust all your style classes

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +.nav-links {
I would recommend to avoid naming classes like arrays. Apply `nav-link-container` or `nav-link-wrapper`.

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +    z-index: 100;
move all z-indexes to global css variables

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.tsx
> +                            <Typography variant="nav" color="primary" text={translate('Landing.Header.Nav.Option.1')} />
create your own component that will create `a` tag instead

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Layout/Layout.tsx
> +import Header from '../Header/Header'
create index.ts file in which you will export your component as a default. Last `Header` in your import will be gone

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/translations/en/header.json
> +    "Landing.Header.Nav.Option.1": "RunBotics",
add names instead of digits, it's easy here. Leave numbers for edge cases e.g. we have a single heading but consists of different colors

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/utils/utils.ts
> +export const BENEFITS_SECTION_ID = 'benefits-section';
after all, remove this section postfix

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +    top: $HEADER_HEIGHT + 2px;
what represents this additional height?

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +    overflow-y: scroll;
not sure if we want to keep the scroll all the time

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +    background-image: linear-gradient(to right, $palette-background-primary 8%, hsl(0 0% 100% / 0.2));
can you move each param to local variable for readability?

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +    left: -100%;
is this related to the sliding transition? If yes, then ignore this com

2022-12-21 12:02 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +    z-index: 100;
not sure if all this appearances of zindex are necessary

2023-01-02 09:06 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +    z-index: 100;
scss variable would be better

2023-01-02 09:06 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.tsx
> +                            <Typography variant="nav" color="primary" text={translate('Landing.Header.Nav.Option.1')} />
use NextLink

2023-01-02 09:07 UTC, FranekMarciniak commented
Since we are using scss variables please use camel case in your scss properties

2023-01-04 11:23 UTC, closed without merging