Bugfix/rpa 554
runbotics/runbotics pull request #126
Opened 2023-01-18 12:09 UTC by FranekMarciniak

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-01-18 12:42 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/index.ts
> +    serializableCheck: false
so we can store selected bpmn element

2023-01-18 12:44 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/ActionFormRenderer.tsx
> +            //@ts-ignore
i don't how to type this function, code is taken from @Stanlee77

2023-01-18 14:16 UTC, preludium requested changes

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/providers/ModelerProvider.tsx
> +interface ModelerProviderProps {
its the same as `ModelerContext` so maybe do it like
`type ModelerProviderProps = ModelerContext;`

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Process/Process.reducers.ts
> +export const resetSelectedElement = (state: ProcessState) => {
maybe just `resetSelection`?

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/BpmnModeler/BpmnModeler.config.ts
> +export const BpmnModelerConfig = (offsetTop: number) => {
I would make it lowercase cause it's not a class or component. Furthermore, it's a function so it would be more appropriate to name it `getBpmnModelerConfig`

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/BpmnModeler/BpmnModeler.utils.ts
> +export const openBpmnDiagram = async (
I would not think that this function will return an array of activities. Rename it please or rearrange it cause open modeler is just 1 step of 10

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/BpmnModeler/BpmnModeler.utils.ts
> +export const getModelerActivities = modeler => {
duplication of logic from `openBpmnDiagram`

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/ActionFormRenderer.tsx
> +            //@ts-ignore
I believe that it has to be done this way cause after all the key you provide is of type `string`  instead of exact translation key

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/ActionFormRenderer.tsx
> +            //@ts-ignore
move usage of capitalize... to a const for better readability

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/ActionFormRenderer.tsx
> +        const bpmnHelper = BPMNHelper.from(modelerRef.current);
does it have to be a ref? If not then why not use just state in the context? It will be shorter

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/ActionFormRenderer.tsx
> +            {defaultFormData &&
move condition to the const

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/Actions/LoopActionRenderer.tsx
>      const isLoopElement = (ele: unknown): ele is BpmnSubProcess =>
rename it to `element`, lets avoid abbreviations

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/Actions/LoopActionRenderer.tsx
> +        (ele as BpmnSubProcess)?.businessObject?.loopCharacteristics !==
this type guard is way too loose imo, lets make it more strict

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/Actions/LoopActionRenderer.tsx
> +        if (loopType === 'Repeat') {
maybe enum?

2023-01-18 14:16 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/utils.ts
> +export const getFormData = (selectedElement: BPMNElement, action?: IBpmnAction) => {
I dont get it, need to discuss it

2023-01-18 18:45 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/utils.ts
> +export const getFormData = (selectedElement: BPMNElement, action?: IBpmnAction) => {
sure

2023-01-19 13:09 UTC, preludium approved these changes

2023-01-19 13:14 UTC, merged