[RPA-674]: Hero section gradient
runbotics/runbotics pull request #180
Opened 2023-03-31 09:54 UTC by Klau-Sam

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-04-03 06:02 UTC, FranekMarciniak requested changes, later dismissed

2023-04-03 06:02 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/BotProcessRunner.tsx
> +    if (rerunProcessInstance && (!isProcessAttended || !rerunInput || Object.keys(rerunInput?.variables).length === 0)) {
process runner inside landing page pr?

2023-04-06 06:42 UTC, preludium submitted a review, later dismissed

2023-04-06 06:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/BotProcessRunner.tsx
> +    if (rerunProcessInstance && (!isProcessAttended || !rerunInput || Object.keys(rerunInput?.variables).length === 0)) {
chill, it's planned

2023-04-06 07:22 UTC, Klau-Sam commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/BotProcessRunner.tsx
> +    if (rerunProcessInstance && (!isProcessAttended || !rerunInput || Object.keys(rerunInput?.variables).length === 0)) {
👍

2023-04-06 08:19 UTC, preludium approved these changes

2023-04-06 08:22 UTC, merged