Customization of mobile heder - alignment elments, addition  log in b…
runbotics/runbotics pull request #187
Opened 2023-04-05 07:54 UTC by AdriannaSuchomska

…utton inside menu

## Description

![image](https://user-images.githubusercontent.com/92982209/230016763-39d0fbae-1d3f-40ec-8857-ad1be6ebf30b.png)
![image](https://user-images.githubusercontent.com/92982209/230016926-fd07e537-1579-40b9-bf72-c32aa87159d1.png)
![image](https://user-images.githubusercontent.com/92982209/230017020-37a88e4d-0433-4691-9698-91fa83343b9f.png)

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-04-05 08:22 UTC, FranekMarciniak requested changes

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.tsx
> +                headerEl.classList.add(styles.isActive);
maybe instead of selecting element and toggling classes we can just do a ternary inside of header, `${styles.header} ${!isNavExpanded ? styles.isActive : ""}`

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.tsx
> +                headerEl.classList.add(styles.isActive);
that way we avoid selecting elements (which can cause some unpredictable side effects

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.tsx
> +                {/* <button
can we delete that?

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.module.scss
> +        border-color: #F5F5F5;
this should be added to our theme pallete, also delete instead of comenting out. If we need it back we will use git

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.module.scss
> +        // background-image: $palette-background-gradient;
same here

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +    .logInBtn {
i would like .loginButton more, but its a nitpick

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.module.scss
> +            border-top: 2px solid #F5F5F5;
color to palette

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.module.scss
> +                height: 18vh;
(；一_一) i dont like it

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.module.scss
> +            height: 18vh;
same here

2023-04-05 08:22 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.tsx
> +                {/* <li className={styles.listItem}>
delete

2023-04-06 06:53 UTC, preludium requested changes

2023-04-06 06:53 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.tsx
> +                headerEl.classList.add(styles.isActive);
+1, much better way. QuerySelector does not belong to react style

2023-04-06 06:53 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +        background-color: #FFFFFF;
imo there should be a global variable that you can use here

2023-04-18 12:11 UTC, preludium requested changes

2023-04-18 12:11 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +        background-color: #FFFFFF;
bump

2023-04-18 12:11 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.tsx
> +                    <Link className={styles.loginButton} href="/login">
hmm, so is it link or button?

2023-04-19 06:31 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.tsx
> +                    <Link className={styles.loginButton} href="/login">
both.

2023-05-02 14:28 UTC, preludium requested changes
if the attached images are up to date then you should adjust the font size on mobile devices

2023-05-02 14:28 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.tsx
> +    const { query, push } = useRouter();
query is not in use, delete it

2023-05-02 14:28 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Navbar/Navbar.tsx
> +    const { query, push } = useRouter();
same

2023-05-02 14:28 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Header/Header.module.scss
> +        margin-right: $margin-2;
trailing spaces after semicolon

2023-05-04 05:12 UTC, preludium approved these changes, later dismissed

2023-05-09 08:20 UTC, merged