[feature/RPA-681]: Reusable carousel mechanism
runbotics/runbotics pull request #190
Opened 2023-04-06 12:59 UTC by Klau-Sam

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-04-19 15:26 UTC, Stanlee77 approved these changes, later dismissed
just cosmetic changes

2023-04-19 15:26 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Carousel/Carousel.tsx
> +                    slides.slice(activeIndex, activeIndex + sliderWidth)}
refactor using "If" component

2023-04-19 15:26 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Carousel/Carousel.tsx
> +                    {slides.length}
imo use If component

2023-04-19 15:26 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/BenefitsSection/BenefitsCarousel/BenefitsCarousel.module.scss
> +    margin: 0 $margin-2;
$margin-0 looks more coherent

2023-04-19 15:26 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/BenefitsSection/BenefitsSection.utils.ts
> +        imageAlt: 'beach icon',
there's no need to specify in alt that it's an 'icon'. Screen reader knows and announces that.

2023-04-19 15:26 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/BenefitsSection/BenefitsSection.utils.ts
> +        imageAlt: 'Hourglass icon',
as above

2023-04-19 15:26 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/BenefitsSection/BenefitsSection.utils.ts
> +        imageAlt: 'Layers icon',
as above

2023-04-19 15:27 UTC, Stanlee77 commented
+ bump app version

2023-04-19 15:41 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/IndustriesSection/IndustriesSlide/IndustriesSlide.module.scss
>              height: $SLIDE-OPEN-IMG;
unclear var name  $SLIDE-OPEN-IMG -> should contain keyword WIDTH/MARGIN/PADDDING/HEIGHT/etc.

first use as HEIGHT, few lines lower as MARGIN-TOP

2023-04-20 10:59 UTC, preludium requested changes

2023-04-20 10:59 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Carousel/Carousel.module.scss
> +            transform: translate(-5px, calc(20px - 90px));
what are these calc elements? name it or otherwise this calc is redundant imo

2023-04-20 10:59 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Carousel/Carousel.tsx
> +const Carousel: FC<CarouselProps> = ({ slides, subsetSize = 1, customStyles, useCSSSlider, hasCounter, hideControlsOnEdge }) => {
dont name props or other consts with `use` prefix, its reserved for hooks

2023-04-20 10:59 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/BenefitsSection/BenefitsCarousel/BenefitsCarousel.module.scss
> +        width: calc(100% - 20px);
can you name this `20px`

2023-04-20 10:59 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/BenefitsSection/BenefitsCarousel/BenefitsCarousel.module.scss
> +            transform: translate(-5px, calc(20px - 90px));
same

2023-04-20 10:59 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/Carousel/Carousel.tsx
> +                    {<div className={styles.slider} ref={sliderRef}>
redundant curlies

2023-04-20 12:01 UTC, preludium submitted a review, later dismissed

2023-04-20 13:40 UTC, preludium approved these changes

2023-04-20 13:42 UTC, merged