[RPA-670] Adds snackbars for register and login errors
runbotics/runbotics pull request #221
Opened 2023-05-25 11:22 UTC by bhszewczyk

- Refactor of login and register page - extracts schema to another file and form logic to another variable
- Adds snackbar with custom messages depending on the error code (disappears after 10 seconds)
- Adds English and Polish versions

Example for registration error with status 500:
![image](https://github.com/runbotics/runbotics/assets/61866178/fa527364-2522-47e0-bc2f-4f20c8645fb0)

Example for login error with status 401
![image](https://github.com/runbotics/runbotics/assets/61866178/96867786-a31a-4c94-a2b5-c292519003b5)

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-06-05 09:07 UTC, preludium requested changes

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/routing/LoginPage/index.tsx
> +/* eslint-disable complexity */
complexity was removed in the meantime

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/auth/RegisterView/index.tsx
> +        values: typeof initialValues,
create an interface for form state. As for now type for submit is any (spoiler, we don't want that)

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/login.json
> +    "Login.SwitchToRegisterMessage": "Nie masz konta? Zapisz się",
I know its not yours but `Zapisz się` fits in english but in polish it doesnt imo. Change it to something like `Zarejestruj się`

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/login.json
> +    "Login.Error.400": "Serwer nie był w stanie przetworzyć żądania ze względu na nieprawidłowe sformułowanie lub niepoprawną składnię",
tbh as a non-technical user I wouldn't understand this 400 message. 400 in case of login can appear only when some field is missing or `rememberMe` won't be boolean, so user cannot achieve it via user interface. imo this error indicates that we fucked up so maybe just display 401 error

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/login.json
> +    "Login.Error.500": "Wystąpił problem z serwerem. Spróbuj ponownie później a jeśli problem się utrzymuje - skontaktuj się z nami poprzez formularz na stronie głownej",
maybe a little shorter: `Wystąpił problem z serwerem. Gdyby problem się powielał skontaktuj się z nami poprzez formularz na stronie głownej`

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/register.json
> +    "Register.Error.400": "Serwer nie był w stanie przetworzyć żądania ze względu na nieprawidłowe sformułowanie lub niepoprawną składnię lub użytkownik już istnieje",
imo make 400 error message just `Niepoprawny format danych lub dany email jest już zajęty`

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/register.json
> +    "Register.Error.500": "Wystąpił problem z serwerem. Spróbuj ponownie później a jeśli problem się utrzymuje - skontaktuj się z nami poprzez formularz na stronie głownej",
copy paste similar error message from login

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/login.json
mirror comments I suggested in pl translations

2023-06-05 09:07 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/register.json
mirror comments I suggested in pl translations

2023-06-12 10:05 UTC, preludium requested changes

2023-06-12 10:05 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/auth/RegisterView/index.tsx
> +                router.push('/app/processes', null, { locale:router.locale });
after positive registration we want to move user to the login page not the application itself

2023-06-12 10:05 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/login.json
> +    "Login.Error.401": "Authentication failed",
merge all 400 errors into one + add message about incorrect data

2023-06-12 10:26 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/auth/RegisterView/index.tsx
> +                router.push('/app/processes', null, { locale:router.locale });
you mean main page and not login page since the e-mail needs to be accepted, right?

2023-06-12 12:25 UTC, preludium approved these changes

2023-06-12 12:25 UTC, merged