feat(runbotics-orchestrator-ui): :lipstick: Tags appearance change
runbotics/runbotics pull request #227
Opened 2023-06-01 12:37 UTC by Klau-Sam

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-06-02 10:10 UTC, preludium requested changes
adjust link element + bump app version

2023-06-02 10:10 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/BlogPostView/BlogPostView.tsx
> +    ));
tbh dont know why href and onClick at the same time. Imo href is enough, on click is doing the same. Remove onClick property and all whats connected to it

2023-06-05 09:44 UTC, Klau-Sam commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/BlogPostView/BlogPostView.tsx
> +    ));
![image](https://github.com/runbotics/runbotics/assets/63171496/08cff696-f13b-4573-97b4-27e65437f419)

2023-06-05 10:29 UTC, preludium approved these changes

2023-06-05 10:32 UTC, merged