Widget for passing files into attended process
runbotics/runbotics pull request #23
Opened 2022-09-21 18:48 UTC by FranekMarciniak

2022-09-21 19:18 UTC, FranekMarciniak commented
Schema przyładowego formularza
```
    {"schema": {
        "type": "object",
        "properties": {
            "file": {
                "title": "Attach file",
                "type": "string"
            },
            "anotherVariable": {
                "title": "Variable",
                "type": "string"
            }
        },
        "required": []
    },
    "uiSchema": {
        "ui:order": [
            "anotherVariable",
            "file"
        ],
        "file": {
            "ui:widget": "FileDropzone"
        }
    },
    "formData": {
        "file": "",
        "anotherVariable": ""
    }
}

2022-09-21 19:21 UTC, FranekMarciniak commented
Done stuff:

- Rjsf dropzone widget capable of drag and drop
- Styled Widget
- Uploding files to sharepoint from scheduler

Stuff TODO:

-  Clear temp after process is run not implemented

2022-09-21 19:25 UTC, FranekMarciniak commented
Example bpmn process using this widget (remeber to add schema and make process attended) is a gist because github does not support .bpmn extension
https://gist.github.com/FranekMarciniak/85391f558dd857adab5110fd8a3c9866

2022-09-21 19:25 UTC, FranekMarciniak commented
also added bpmn file in jira task

2022-09-21 19:31 UTC, FranekMarciniak commented
Quick rundown of how its working:
We upload file into modal -> 
widget is converting it to base64 (rjsf requires it) -> 
scheduler searches through variables to find if there are any files attached -> 
if there are, gets sherepoint token (for scheduler env contact @preludium) -> 
upload file to temp dir -> 
get download link from file id -> 
mutate variables object to replace base64 file with download link ->
use download link in `Download file` action (in API group)

2022-09-21 19:34 UTC, FranekMarciniak commented
Stuff to impove:
Better feedback of whats happning to user

2022-09-26 09:19 UTC, FranekMarciniak commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +    private readonly CALLBACK_URL = 'http://localhost:3000';
Not sure if this will work in production

2022-09-26 09:41 UTC, preludium requested changes

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/components/AttendedProcessModal/AttendedProcessModal.tsx
> +    useAsyncEffect(async () => {}, []);
seems redundant, remove it with imports

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/FileDropzoneWidget.tsx
> +const getColor = (props: DropzoneRootProps) => {
move styled-components, interfaces and util fn to appropriate files

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/FileDropzoneWidget.tsx
> +    isDragAccept?: boolean;
those 2 props should be rephrased, e.g. `isDragAccepted`

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/FileDropzoneWidget.tsx
> +    const [file, setFile] = React.useState(null);
type for usestate would be nice :)

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/FileDropzoneWidget.tsx
> +                setFile(reader.result as string);
setting state in the loop? it doesn't seem right

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/FileDropzoneWidget.tsx
> +        acceptedFiles.forEach((file) => {
same name as state above `file`, misunderstanding possible

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/FileDropzoneWidget.tsx
> +        props.onChange(file);
imo u can call directly where u set the state

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +    private readonly TENANT_ID = process.env.SHAREPOINT_TENANT_ID;
use `ServerConfigService` to retrieve envs

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +@Injectable({ scope: Scope.DEFAULT })
what is scope doing in this case?

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +    private session: AuthData = {
`AuthData` type does not accept undefined fields, you need to include it in the interface

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +export interface AuthData {
move interface to another file

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +        const CancelToken = Axios.CancelToken.source();
our variables should be in camel case, do not bother with axios naming convention

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +        const tokens = Axios
token or tokens? provided type in axios says that there will be single token

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/auth.module.ts
> +    exports: [AuthService, PassportModule, MicrosoftSession],
fyi, you don't have to export it if it is used only in the same module in which you use it (analyze your case)

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/scheduler/scheduler.service.ts
> +      .catch(err => {
include info about the kind of the token, could be mistaken with jwt access token in logs

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/scheduler/upload/upload-files.service.ts
> +export class UploadFilesService {
rename it to `FileUploadService`

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/scheduler/upload/upload-files.service.ts
> +    private TOKEN: string = '';
if it is not readonly then use camelcase

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/scheduler/upload/upload-files.service.ts
> +            results = results.concat(
maybe just `results.push`? no assignment required

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/scheduler/upload/upload-files.service.ts
> +    static makeRequest() {
make spaces between functions, interfaces and so on

2022-09-26 09:41 UTC, preludium commented on runbotics/runbotics-scheduler/src/scheduler/upload/upload-files.service.ts
> +interface APICell {
move interfaces to another file

2022-09-26 09:42 UTC, preludium commented
do we have any ui response in case of an error? it should be

2022-09-29 10:11 UTC, preludium approved these changes, later dismissed

2022-09-29 10:11 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/FileDropzone/FileDropzone.utils.tsx
> +        return '#00e676';
can you use colors from mui palette?

2022-09-29 10:11 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/index.tsx
> +    FileDropzone: FileDropzoneWidget,
nothing wrong with a widget in the name imo, thanks to it we are letting know that it is custom

2022-09-29 10:11 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +    private readonly CALLBACK_URL = 'http://localhost:3000';
was it here before? or this is a new one?

2022-09-29 10:11 UTC, preludium commented on runbotics/runbotics-scheduler/src/auth/microsoft.session.ts
> +    private readonly CALLBACK_URL = 'http://localhost:3000';
maybe you can use entrypoint url from env

2022-09-29 12:14 UTC, preludium approved these changes

2022-09-29 12:16 UTC, merged