[RPA 750] Highlight the process that caught an error
runbotics/runbotics pull request #236
Opened 2023-06-15 09:15 UTC by MRSIMM0

## Description

![image](https://github.com/runbotics/runbotics/assets/44839807/de2b2dcd-35a9-4b97-ae2e-1b0be93846aa)

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-06-15 10:21 UTC, preludium requested changes
It's missing database migration

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-common/src/bpmn/tasks.ts
> +
redundant empty space at the end of enum + please fix typo in `ITERMEDIATE_THROW_EVENT` and in the appearances

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/bpmn/runtime-subscriptions.service.ts
> +                        case 'bpmn:ErrorEventDefinition': //with BpmnElementType.BOUNDARY_ERROR enum it does not work XD
wut, nah it has to work. Try to solve it, if there will be no progress then contact me

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/bpmn/runtime-subscriptions.service.ts
> +                            processInstanceEvent.step = 'event.warning';
the step should be like `event.errorBoundary`, just to be clear everywhere

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/bpmn/runtime-subscriptions.service.ts
> +                        case  BpmnElementType.START_EVENT:
you leave a lot of empty spaces/lines in your code. Please pay attention to it

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Label/Label.tsx
> +    warning?:boolean
space after colon!

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Label/Label.tsx
> +        {warning && isProcessInstanceFinished(ProcessInstanceStatus[children.toString()])?
`children.toString()` seems like a hack, rewrite it correctly

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-scheduler/src/websocket/bot/process-launch/bot-process-instance-event.service.ts
> +    return processInstanceEvent.step === 'event.warning';
IMO we should have a single source of truth for elements like `event.warning`

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-scheduler/src/websocket/bot/process-launch/bot-process-instance-event.service.ts
> +    return processInstanceEvent.step === 'event.warning';
the name `setWarning` sounds like a setter in a class or manipulation of the parameter. A better term would be `hasWarning` (in the ideal world I would include the name `processInstance` in it but we can deduct if from parameter)

2023-06-15 10:21 UTC, preludium commented on runbotics/runbotics-scheduler/src/websocket/bot/process-launch/bot-process-instance-event.service.ts
> +                        ? {
manipulate just a warning field with this function
`
{
    error: processInstanceEvent.error,
    step: processInstanceEvent.step,
    warning: hasWarning(processInstanceEvent.step),
}
`

2023-06-15 10:21 UTC, preludium commented on runbotics-orchestrator/.jhipster/ProcessInstance.json
> +      }
redundant, we don't use it. It was relevant only at the project initialization

2023-06-15 12:58 UTC, MRSIMM0 commented on runbotics/runbotics-desktop/src/core/websocket/bpmn/runtime-subscriptions.service.ts
> +                        case 'bpmn:ErrorEventDefinition': //with BpmnElementType.BOUNDARY_ERROR enum it does not work XD
forgot to delete that comment

2023-06-15 13:48 UTC, preludium requested changes

2023-06-15 13:48 UTC, preludium commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20230615123802_changelog.xml
> +    <changeSet author="samelakk" id="20230615123802">
are you `samelakk` or `pasiecznys`? xd

2023-06-15 13:48 UTC, preludium commented on runbotics/runbotics-common/src/model/api/process-instance.model.ts
> +    WARNING = 'event.warning'
not warning but errorBoundary

2023-06-15 13:48 UTC, preludium commented on runbotics/runbotics-common/src/bpmn/tasks.ts
> +  BOUNDARY_ERROR = 'bpmn:errorBoundary'
it should be ` BOUNDARY_ERROR = 'bpmn:ErrorEventDefinition'`

2023-06-15 13:48 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/bpmn/runtime-subscriptions.service.ts
> +                        case 'bpmn:ErrorEventDefinition':
use enum

2023-06-15 13:48 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/process.json
> +    "Process.Details.Modeler.Actions.Event.Warning.Label": "Ostrzerzenie",
ostrzeżenie*

2023-06-15 13:50 UTC, MRSIMM0 commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20230615123802_changelog.xml
> +    <changeSet author="samelakk" id="20230615123802">
My mistake XD

2023-06-16 09:19 UTC, preludium approved these changes, later dismissed

2023-06-16 09:36 UTC, preludium approved these changes

2023-06-16 09:37 UTC, merged