[RPA 804] Create CRON job to delete saved guest accounts.
runbotics/runbotics pull request #248
Opened 2023-07-04 07:12 UTC by MRSIMM0

## Description

Created CROM job to delete all gust accounts every day at midnight.

Added trigger to delete processes of those guests. 

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-07-05 08:09 UTC, Stanlee77 requested changes
nice

2023-07-05 08:09 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/web/rest/GuestResource.java
> +        return ResponseEntity.noContent().headers(HeaderUtil.createAlert(applicationName, "guestManagement.deleted","All")).build();
format - add NL

2023-07-05 08:09 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/web/rest/GuestResource.java
> +     * {@code DELETE /api/guest/delete/all} : delete the "login" User.
> delete the "login" User.

i belive it "deletes all guests"

2023-07-05 10:05 UTC, Stanlee77 submitted a review, later dismissed

2023-07-05 11:53 UTC, Stanlee77 approved these changes

2023-07-05 11:54 UTC, merged

2023-07-06 07:26 UTC, preludium commented on runbotics-orchestrator/src/main/java/com/runbotics/web/rest/GuestResource.java
> +@RequestMapping("/api/guest")
guests*. API resources should be in the plural form

2023-07-06 07:26 UTC, preludium commented on runbotics-orchestrator/src/main/java/com/runbotics/web/rest/GuestResource.java
> +    @DeleteMapping("/delete/all")
the information about the delete is in the endpoint mapping so leave just `/all`