[feature/RPA-843] Create execution counter and session timer for guest view
runbotics/runbotics pull request #271
Opened 2023-07-12 14:57 UTC by marcin-depcik

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-07-12 16:35 UTC, Stanlee77 requested changes

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/repository/GuestRepository.java
> +    @Query(value = "SELECT * FROM guest WHERE user_id = ?1", nativeQuery = true)
never use SELECT * as final query

if there's new column added (or one removed) to guest this can result in too much or too less data.

replace with SELECT g.login, g.first_name, [...] FROM guest g WH...

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/service/impl/GuestServiceImpl.java
> +        var guestOptional = guestRepository.findGuestById(id);
try to not use var 
replace with Optional<Guest> or even better -> just return guestRepository.findGuestById(id)

Also I've seen direct uses of [...]Repository in [...]Resource files but I guess it's an antipattern

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/layouts/MainLayout/TopBar/index.tsx
> +            fontSize: '0.875rem',
use theme.typography.h6 -> h6 is 14px = 0.875rem

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/layouts/MainLayout/TopBar/index.tsx
> +                fontWeight: 700,
use theme.typography.fontWeightBold -> it's 700

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/layouts/MainLayout/TopBar/index.tsx
> +        margin: '0.85rem',
you can experiment with theme.spacing(2) but tbh idk how it works xD

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/layouts/MainLayout/TopBar/index.tsx
> -
that's right! no mercy for 
<img width="167" alt="image" src="https://github.com/runbotics/runbotics/assets/69820069/bee32c64-cdc6-498a-b604-ec81c674fe8d">

2023-07-12 16:35 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/layouts/MainLayout/TopBar/index.tsx
> +        }
it's just one dispatch -> imo it's better to use then & catch

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Guests/Guests.reducers.ts
> +        const { exp: expirationTime }: any = jwtDecode(accessToken);
avoid using any

what I'd do:
1. create new file slices.types.ts in slices/
2. create new interface for { exp: expirationTime } there
3. used the interface **here** and in Auth.thunks (grep "any")

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Guests/Guests.slice.ts
> +export const EXECUTION_LIMIT = 10;
now there's more than one source of truth -> there's GUEST_EXECUTION_LIMIT in runbotics-scheduler

imo bring it up to runbotics-common

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Guests/Guests.slice.ts
> +export const EXECUTION_LIMIT = 10;
also avoid 
![image](https://github.com/runbotics/runbotics/assets/69820069/db82456b-899a-4f40-b60b-d8e312d860af)
 between imports

2023-07-12 16:35 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/demo.json
> +    "Demo.Session.Timer": "Zegar Sesji:"
WDYT about "Pozostało:" lub "Do końca sesji:"
odpowiednio remaing/session ends in

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useTimer.ts
> +        return { hours, minutes, seconds };
we expect session can last more than 1 hour?
just sayin'

2023-07-12 16:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useTimer.ts
> +                }
keep in oneline

2023-07-13 12:42 UTC, preludium approved these changes, later dismissed

2023-07-13 12:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/BotProcessRunner.tsx
> +    const guestExecutionLimitExceeded = isGuest && executionsCount >= EXECUTION_LIMIT;
all of this can be replaced by `useRole` hook

2023-07-13 12:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useTimer.ts
> +    const interval = useRef(null);
lets make a type for it

2023-07-13 12:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useTimer.ts
> +                typeof callback === 'function' && callback();
chill, it's TypeScript not JS just use it `callback?.()`

2023-07-13 12:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useTimer.ts
> +        return { hours, minutes, seconds };
seems like this useCallback is useless cause its rerendering every second

2023-07-13 12:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/BotProcessRunner.tsx
> +
add tooltip message if guest used all the process execution limit

2023-07-13 12:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/layouts/MainLayout/TopBar/CountdownTimer.tsx
> +const CountdownTimer: FC<{ remainingTime: number, callback?: () => void }> = ({ remainingTime, callback }) => {
create an interface for better readability

2023-07-13 12:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Guests/Guests.thunks.ts
> +    async (payload: { userId: string }, { rejectWithValue }) => {
there is a type already defined next to createAsyncThunk

2023-07-13 12:42 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Guests/Guests.thunks.ts
> +            return { ...guest };
no need to create new object here

2023-07-13 12:56 UTC, merged