[RPA-850] Hero section scaling fix
runbotics/runbotics pull request #275
Opened 2023-07-14 09:54 UTC by Aeri4a

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-07-14 09:55 UTC, Aeri4a reviewed
self-rev

2023-07-14 10:08 UTC, preludium requested changes, later dismissed

2023-07-14 10:08 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/HeroSection/HeroBackground/HeroBackground.module.scss
> +@media (min-height: 700px) {
stick to defined breakpoints in breakpoint css file

2023-07-14 10:10 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/HeroSection/HeroBackground/HeroBackground.module.scss
> +@media (min-height: 700px) {
media queries are designed to work with the width property. Try to solve it the other way

2023-07-14 10:54 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/HeroSection/HeroBackground/HeroBackground.module.scss
> +@media (min-height: 700px) {
we're implementing desktop-first approach - try to use only max-width

2023-07-14 10:54 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-landing/views/sections/HeroSection/HeroBackground/HeroBackground.module.scss
> +    height: 1000px;
if you have const value move it to the top of the file to const var e.g.:
HAND_WRAPPER_HEIGHT: 1000px;

2023-07-17 10:37 UTC, Stanlee77 reviewed
bump version

2023-07-17 10:42 UTC, Stanlee77 approved these changes

2023-07-17 10:49 UTC, merged