[RPA-796] Adds endpoint for user partial update
runbotics/runbotics pull request #313
Opened 2023-07-31 12:08 UTC by bhszewczyk

## Description

Before:
- once registered (no matter registration language) and the logged in site was always in English
- if the user was logged in and changed the language the database was not updated hence on the translation was always in English

Now:
- allows user to update first name, last name, email, language and image url
- saves chosen language to database on register
- once language is changed by the use when on the /app view database is updated - on next login chosen language translations are applied 

![image](https://github.com/runbotics/runbotics/assets/61866178/3307f256-af29-44cd-add1-bfc13b2bc2f2)
![image](https://github.com/runbotics/runbotics/assets/61866178/0a61a80e-c446-4e8c-b961-9a6759ac94e8)

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-07-31 14:06 UTC, Stanlee77 requested changes

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/service/dto/AccountPartialUpdateDTO.java
> +//    private Set<UpdatedKeys> updatedKeys;
left out comment

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/service/dto/AccountPartialUpdateDTO.java
> +
comment left out

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/LanguageSwitcher/LanguageSwitcher.tsx
> +    const updateLanguageInDB = async (patchPayload: IUser) => {
avoid linking words -> replace with updateDatabaseLanguage

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/LanguageSwitcher/LanguageSwitcher.tsx
> +        updateLanguageInDB({langKey: language});
it's object add spaces inside {}

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/LanguageSwitcher/LanguageSwitcher.tsx
> +
oh boy, what a change!

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/LanguageSwitcher/LanguageSwitcher.tsx
> +        await dispatch(usersActions.partialAccountUpdate(patchPayload));
how about just a partialUpdate? 

when called usersActions.partialUpdate - everything's clear

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/LanguageSwitcher/LanguageSwitcher.tsx
>  import styles from './LanguageSwitcher.module.scss';
shrink it up

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-landing/components/LanguageSwitcher/LanguageSwitcher.tsx
>  import styles from './LanguageSwitcher.module.scss';
the newlines ofc

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/types/user.ts
> +    langKey?: 'en' | 'pl';
use type Language from translations.ts or experiment with it

to have one source of truth -> in case we add new language

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Users/Users.thunks.ts
>  );
format it just like `getAllLimited`

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Users/Users.extraReducers.ts
>          });
there are gonna be conflicts with Anna's current task - you both use state.loading in Users.extraReducers. Try to be more specific (like change state.loading to state.updateUserLoading or create nested object state.userUpdate.loading (i recommend this one)

source:
https://github.com/runbotics/runbotics/blob/aec8605eb6a3812cc6e2afa09f17b9165ce0aaa3/runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/Users/Users.extraReducers.ts

2023-07-31 14:06 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/web/rest/AccountResource.java
> +        var user = userService.getUserWithAuthorities().get();
Replace var with User

2023-08-01 09:55 UTC, Stanlee77 approved these changes
Lookin' good for me.

2023-08-01 11:10 UTC, Klau-Sam approved these changes

2023-08-01 11:24 UTC, merged