[RPA-630] Delete webapp
runbotics/runbotics pull request #332
Opened 2023-08-10 08:01 UTC by marcin-depcik

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-08-10 08:40 UTC, MRSIMM0 requested changes

2023-08-10 08:40 UTC, MRSIMM0 commented on runbotics-orchestrator/package.json
Delete package.json

2023-08-10 08:40 UTC, MRSIMM0 commented on runbotics-orchestrator/tsconfig.json
also delete this

2023-08-11 08:56 UTC, MRSIMM0 approved these changes

2023-08-16 07:06 UTC, preludium approved these changes
bump `runbotics-cli` version

2023-08-16 09:21 UTC, merged