[RPA-842-2] Endpoint to edit users
runbotics/runbotics pull request #339
Opened 2023-08-16 08:49 UTC by Aeri4a

## Description

## Motivation and Context

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-08-16 12:37 UTC, Stanlee77 submitted a review, later dismissed
I've read your JIRA comment. We should return error when someone tries to change any of forbidden fields like lastModified date, createdDate, etc. Not setting them is not enough

2023-08-16 18:30 UTC, preludium requested changes

2023-08-16 18:30 UTC, preludium commented on runbotics-orchestrator/src/main/java/com/runbotics/service/UserService.java
> +
it would be more than welcome to have it as a single sql operation

2023-08-16 18:30 UTC, preludium commented on runbotics-orchestrator/src/main/java/com/runbotics/service/UserService.java
> +
it would be more than welcome to have it as a single sql operation

2023-08-17 12:35 UTC, preludium approved these changes

2023-08-17 12:44 UTC, merged