[feature/RPA-948] Block editing/deleting process for other than admin and owner
runbotics/runbotics pull request #372
Opened 2023-08-31 06:49 UTC by marcin-depcik

## Description

<img width="959" alt="image" src="https://github.com/runbotics/runbotics/assets/82586165/ec33852d-fdf9-4024-8f0d-ceed3f1e6004">

<img width="959" alt="image" src="https://github.com/runbotics/runbotics/assets/82586165/f77b60fe-4810-4759-b462-c5cdb8d27b76">

<img width="960" alt="image" src="https://github.com/runbotics/runbotics/assets/82586165/3cedd237-a4e5-4a60-90c8-ad1535e526f4">

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-09-01 09:22 UTC, bhszewczyk commented
What is the purpose of making oprtion "Edit" available to click if there is nothing we can edit in modal? 😃 I think it should be greyed out just like the delete button.

2023-09-01 10:34 UTC, preludium requested changes

2023-09-01 10:34 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/DeleteProcess.tsx
> +const DeleteProcess = ({ process, disabled = false }: DeleteProcessProps) => {
I know its not yours but it does not sound like function component. Stick to `The Boy Scout Rule` if it does not go far beyond your task

2023-09-05 12:58 UTC, preludium approved these changes

2023-09-05 12:58 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useProcessOwner.ts
> +    const userId = typeof user.id === 'number' ? user.id : Number(user.id);
can userId be NaN?

2023-09-05 14:48 UTC, preludium approved these changes

2023-09-05 15:03 UTC, merged