[feature/RPA-949] Block editing/deleting global variables for users other than admin and owner
runbotics/runbotics pull request #376
Opened 2023-09-01 08:51 UTC by marcin-depcik

## Description

<img width="960" alt="image" src="https://github.com/runbotics/runbotics/assets/82586165/fdd2750c-995e-451d-b6d5-a8be4b3bf312">

<img width="960" alt="image" src="https://github.com/runbotics/runbotics/assets/82586165/3a991b69-b225-4622-893e-34c3c6320735">

<img width="959" alt="image" src="https://github.com/runbotics/runbotics/assets/82586165/b33fa20f-8102-4dfb-879b-bf2f36b391d3">

DONE:
1. block the option to edit a global variable for anyone who is not an admin or owner of the variable
2. block the option to delete a global variable for anyone who is not an admin or owner of the variable
3. add a variable creator column in the table

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-09-01 08:54 UTC, marcin-depcik commented
Requires testing new migration after adding changes from master branch

2023-09-01 10:27 UTC, preludium requested changes

2023-09-01 10:27 UTC, preludium commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20230831151264_changelog.xml
> +            WHERE creator_id ISNULL;
not sure if postgres supports `ISNULL` expression, add a space there

2023-09-01 10:27 UTC, preludium commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20230831151264_changelog.xml
> +        />
move foreignkey creation to another changeset in case we want to get rid of this in the future

2023-09-01 10:27 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/variables.json
> +    "Variables.ListView.Table.Header.CreatedBy": "Utworzony przez",
`Twórca` or `Właściciel`

2023-09-01 10:27 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/types/model/global-variable.model.ts
> +export type Creator = Pick<IUser, 'id' | 'login'>;
maybe name it like `UserDTO`, it can be useful in other places

2023-09-01 10:27 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/variable/VariableListView/Table/useGlobalVariablesColumns.tsx
>                  };
just filter action elements from list if we don't want user to use it

2023-09-05 13:21 UTC, preludium approved these changes

2023-09-06 06:17 UTC, merged