[RPA-991] Adds new Excel Cloud action: Create worksheet
runbotics/runbotics pull request #407
Opened 2023-09-19 13:22 UTC by bhszewczyk

## Description

- adds new action: Create worksheet
![image](https://github.com/runbotics/runbotics/assets/61866178/d13359a5-c3f4-4880-9d75-04d95d03fbc3)
- changed regex for worksheet name to limit number of characters to 31
- adds a tooltip with information about character limit and not allowed characters
- output (worksheet name) is optional
- left default error if worksheet name already exists:
![image](https://github.com/runbotics/runbotics/assets/61866178/bb8e6a31-c0f1-4d9e-b195-4eb96521bb77)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-09-19 13:52 UTC, marcin-depcik requested changes

2023-09-19 13:52 UTC, marcin-depcik commented on runbotics/runbotics-desktop/src/action/microsoft/excel/excel.service.ts
> +        return worksheetName;
If this is possible, it would be better to return worksheet name retrieved from the response object.

2023-09-19 13:52 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/process/process.json
> +    "Process.Details.Modeler.Actions.CloudExcel.CreateWorksheet.WorksheetName.Info": "Maximum number of characters: 31. Characters not allowed: \\ , / , * , ? , : , [ , ]",
shouldn't be `allowed: \ , / , * , ? , : , [ , ]`?

2023-09-19 13:52 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/process/process.json
> +    "Process.Details.Modeler.Actions.CloudExcel.CreateWorksheet.WorksheetName.Info": "Maksymalna liczba znaków: 31. Znaki niedozwolone: \\ , / , * , ? , : , [ , ]",
as above

2023-09-19 13:52 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/Actions/cloudExcel.actions.ts
> +
remove empty line

2023-09-19 13:52 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/Actions/cloudExcel.actions.ts
> +
remove empty line

2023-09-20 08:45 UTC, Stanlee77 approved these changes

2023-09-20 08:45 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/process/process.json
> +    "Process.Details.Modeler.Actions.CloudExcel.CreateWorksheet.WorksheetName.Info": "Maximum number of characters: 31. Characters not allowed: \\ , / , * , ? , : , [ , ]",
Imo +"New worksheet name. Maximum 31 characters. Characters not allowed: \\ , / , * , ? , : , [ , ]",

2023-09-20 08:45 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/process/process.json
> +    "Process.Details.Modeler.Actions.CloudExcel.CreateWorksheet.WorksheetName.Info": "Maksymalna liczba znaków: 31. Znaki niedozwolone: \\ , / , * , ? , : , [ , ]",
like in en version

2023-09-20 08:45 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/process/process.json
> +    "Process.Details.Modeler.Actions.CloudExcel.CreateWorksheet.WorksheetName.Info": "Maximum number of characters: 31. Characters not allowed: \\ , / , * , ? , : , [ , ]",
but it's just a suggestion

2023-09-20 08:53 UTC, marcin-depcik approved these changes

2023-09-20 08:54 UTC, merged