[RPA-345] Action Rework: Api request
runbotics/runbotics pull request #43
Opened 2022-10-10 12:55 UTC by LukaszKaczkowski

2022-10-10 19:42 UTC, FranekMarciniak requested changes

2022-10-10 19:42 UTC, FranekMarciniak commented on runbotics/runbotics-desktop/src/config/BackgroundPageApiRequestHandler.ts
> +                    response = await Axios.delete(compiled, JSON.parse(input.body));
Delete does not need `input.body`

2022-10-10 19:42 UTC, FranekMarciniak commented on runbotics/runbotics-desktop/src/config/BackgroundPageApiRequestHandler.ts
> +                    response = await Axios.delete(compiled, JSON.parse(input.body));
Look at GET method

2022-10-10 19:42 UTC, FranekMarciniak commented on runbotics/runbotics-desktop/src/config/BackgroundPageApiRequestHandler.ts
> +                    response = await Axios.delete(compiled, JSON.parse(input.body));
And add `input.headers`

2022-10-10 19:42 UTC, FranekMarciniak commented on runbotics/runbotics-desktop/src/config/BackgroundPageApiRequestHandler.ts
> +    data?: T;
We can to previous version where data is required

2022-10-10 19:42 UTC, FranekMarciniak commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/Actions/api.actions.ts
> +                                                enum: ['GET'],
Add delete here

2022-10-11 08:37 UTC, preludium requested changes

2022-10-11 08:37 UTC, preludium commented on runbotics/runbotics-desktop/src/config/BackgroundPageApiRequestHandler.ts
> +            this.logger.log(e);
I dont think that we always get the response we always should throw an error. This if statement should be deleted imo

2022-10-11 12:26 UTC, preludium approved these changes, later dismissed

2022-10-11 12:26 UTC, preludium commented on runbotics-orchestrator/build.gradle
> +    buildscript {
redundant space

2022-10-11 12:39 UTC, preludium approved these changes

2022-10-11 12:40 UTC, FranekMarciniak approved these changes

2022-10-11 12:44 UTC, merged