[RPA-629] Changes in process of definition ExclusiveGateway
runbotics/runbotics pull request #456
Opened 2023-11-06 14:04 UTC by damlit

## Description
Better user experience during writing expressions in exclusive gateway/flows.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-11-06 15:36 UTC, preludium requested changes

2023-11-06 15:36 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/renderers/GatewayFormRenderer.tsx
> +    const COLOR_BLACK = '#000000';
isnt it available in our theme?

2023-11-06 15:36 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/renderers/GatewayFormRenderer.tsx
> +    const COLOR_BLACK = '#000000';
imo use useTheme hook to get it

2023-11-06 15:36 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/renderers/GatewayFormRenderer.tsx
> +    const COLOR_BLACK = '#000000';
default theme object is here https://mui.com/material-ui/customization/default-theme/

2023-11-06 15:36 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/renderers/GatewayFormRenderer.tsx
> +    const gateway: IBpmnGateway = selectedElement as IBpmnGateway;
type it only in 1 place

2023-11-06 15:36 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/renderers/GatewayFormRenderer.tsx
> +    };
use `reduce` here to convert list to object

2023-11-06 15:36 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/renderers/GatewayFormRenderer.tsx
> +                    <InputLabel id="default-flow-select-input-label">Default flow</InputLabel>
translation

2023-11-06 15:36 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/renderers/GatewayFormRenderer.tsx
> +                        label="Default"
translation

2023-11-06 15:36 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/FlowLabelForm.tsx
> +        const isSameAsBefore =
`isEqual` imo better, avoid `as` and so on

2023-11-06 15:57 UTC, damlit commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/renderers/GatewayFormRenderer.tsx
> +                        label="Default"
Unnecessary label - removed

2023-11-07 15:29 UTC, preludium approved these changes

2023-11-07 15:30 UTC, merged