[RPA-1116] New variables autocomplete functionality
runbotics/runbotics pull request #473
Opened 2023-11-27 07:34 UTC by Aeri4a

## Description

![image](https://github.com/runbotics/runbotics/assets/80831299/6c27b341-ef5e-4317-b62c-3503dc27ec1c)

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-11-27 10:54 UTC, preludium requested changes
Having issues handling clear on select close? Try to use close related props https://mui.com/material-ui/api/autocomplete/#Autocomplete-prop-clearOnBlur

2023-11-27 10:54 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> +        </StyledBox>
adjust input adornment instead
https://mui.com/material-ui/react-text-field/#input-adornments

2023-11-27 10:54 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> +const inputDetailsDefault = {
upper case and low dash if constant

2023-11-27 10:54 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> +    const analyzeInput = (input: string) => {
more specific function name and created variables

2023-11-28 09:40 UTC, preludium requested changes

2023-11-28 09:40 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> +        const matches = [...input.matchAll(variableRegex)];
more like `variables` imo. I assume that the right side of this line is to retrieve all variables in autocomplete string

2023-11-28 09:40 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> +        const autocompleteResult = matches.find(match => !(optionValues['ui:options'].includes(match[0])));
what is a structure of `matches` right now? 2D list?

2023-11-28 09:40 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> +        const autocompleteResult = matches.find(match => !(optionValues['ui:options'].includes(match[0])));
so here you look for a single variable that is not completed at the moment? if so then then apply this to you variable name

2023-11-28 09:40 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> +    const handleAutocomplete = (event: any, newValue: string) => {
tbh for sure there is type for such event

2023-11-28 09:40 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessBuildView/Modeler/ActionFormPanel/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> +            disableClearable={true}
`={true}` is redundant for boolean props

2023-11-28 10:02 UTC, preludium approved these changes

2023-11-28 11:45 UTC, Aeri4a commented
Gateway & Autocomplete still to fix after rebase

2023-11-28 16:05 UTC, merged