[RPA-1144] Bot-scheduler keep-alive message
runbotics/runbotics pull request #486
Opened 2023-12-12 15:29 UTC by Aeri4a

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2023-12-13 08:23 UTC, preludium requested changes

2023-12-13 08:23 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/listeners/process.listener.ts
> +    private keepAliveStatus: KeepAliveStatus = { intervalId: undefined, isActive: false };
move this object outside class and name it like `initKeepAliveStatus`

2023-12-13 08:23 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/listeners/process.listener.ts
> +        this.keepAliveStatus = { ...this.keepAliveStatus, isActive: false };
assign here init object

2023-12-13 08:23 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/listeners/process.listener.ts
> +    private async stopKeepingConnection() {
I dont like this naming `start/stop keeping connection`
I suggest `beginKeepAliveInterval` and `clearKeepAliveInterval`

2023-12-13 08:23 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/listeners/process.listener.ts
> +    private async stopKeepingConnection() {
additionally, what async about those methods?

2023-12-13 08:23 UTC, preludium commented on runbotics/runbotics-scheduler/src/websocket/bot/bot.gateway.ts
> +
I thought more like creating a custom method updating the bot entity with a single query

bot doesn't care about response status it's more like `If you do something with it or not it's your business`

2023-12-13 15:14 UTC, damlit approved these changes

2023-12-19 16:49 UTC, preludium approved these changes

2023-12-19 17:33 UTC, merged