[RPA-1259] Allow for adding new collections
runbotics/runbotics pull request #535
Opened 2024-01-30 18:47 UTC by Stanlee77

## Description
![image](https://github.com/runbotics/runbotics/assets/69820069/180ee882-b550-4f03-8427-95e2f973da92)
<img width="509" alt="image" src="https://github.com/runbotics/runbotics/assets/69820069/9cafe503-f7a7-45e3-b045-ba6bca79b886">
<img width="656" alt="image" src="https://github.com/runbotics/runbotics/assets/69820069/5d174593-85ad-4afe-8ae7-0365bb233b91">

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-01-31 10:54 UTC, preludium requested changes

2024-01-31 10:54 UTC, preludium commented on runbotics-orchestrator/src/main/java/com/runbotics/domain/ProcessCollection.java
> +import jdk.jfr.BooleanFlag;
whats this import?

2024-01-31 10:54 UTC, preludium commented on runbotics-orchestrator/src/main/java/com/runbotics/repository/ProcessCollectionRepository.java
> +@SuppressWarnings("unused")
seems like you use this repository so remove this warning

2024-01-31 10:54 UTC, preludium commented on runbotics-orchestrator/src/main/java/com/runbotics/security/FeatureKeyConstants.java
> +    public static final String PROCESS_COLLECTION_ADD = "PROCESS_COLLECTION_ADD";
add all possible already e.g. delete and edit

2024-01-31 10:54 UTC, preludium commented on runbotics/runbotics-common/src/collections/process-collections.ts
> +export type ProcessCollectionKeys = { [Key in keyof ProcessCollection]: Key }[keyof ProcessCollection];
what is it for?

2024-01-31 10:54 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/ProcessCollection/ProcessCollection.slice.ts
> +};
let's discuss it

2024-01-31 10:54 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/ProcessCollection/ProcessCollection.extraReducers.ts
> +        })
ideally, here you should update global state and you don't need to fetch all collections once again

2024-02-01 13:54 UTC, preludium requested changes

2024-02-01 13:54 UTC, preludium commented on runbotics-orchestrator/src/main/java/com/runbotics/web/rest/ProcessCollectionResource.java
> +    @PostMapping("process-collection")
wrong feature key

2024-02-01 13:54 UTC, preludium commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240123003633_changelog.xml
I believe that its already on develop brach. Maybe some issues appeard due to history changes on develop branch

2024-02-01 13:54 UTC, preludium commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240123003633_changelog.xml
yup, you have stale commits. Create a new branch after CR fixes and cherry pick your commits

2024-02-02 16:59 UTC, Stanlee77 reviewed
Self reviewed

2024-02-02 16:59 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/ProcessCollection/ProcessCollection.extraReducers.ts
> +        })
thanks for pointing that out

2024-02-02 16:59 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/ProcessCollection/ProcessCollection.extraReducers.ts
> +        })
done & testes

2024-02-02 16:59 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/domain/ProcessCollection.java
> +import jdk.jfr.BooleanFlag;
so removed it

2024-02-02 16:59 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/ProcessCollection/ProcessCollection.slice.ts
> +};
I'm going to be able to discuss this on friday 1p.m.

2024-02-02 16:59 UTC, star-in-the-jar commented on runbotics/runbotics-common/src/collections/process-collections.ts
> +export type ProcessCollectionKeys = { [Key in keyof ProcessCollection]: Key }[keyof ProcessCollection];
There's universal function for handling every change in ModifyDialog form. This type is used to check if the property belongs to ProcessCollection object
<img width="852" alt="image" src="https://github.com/runbotics/runbotics/assets/69820069/33cc5e54-41e4-46f9-9336-8edbf55710a4">

2024-02-02 17:01 UTC, Stanlee77 reviewed
self reviewed

2024-02-06 12:09 UTC, preludium approved these changes

2024-02-06 12:09 UTC, preludium commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240202155800_changelog.xml
to be adjusted

2024-02-06 12:09 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/utils/text.ts
> +    delimiter = ' ',
use `\s` for better readability

2024-02-07 15:45 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/store/slices/ProcessCollection/ProcessCollection.slice.ts
> +};
discussed, done

2024-02-07 15:45 UTC, Stanlee77 commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240202155800_changelog.xml
tested if works, done

2024-02-07 16:08 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/utils/text.ts
> +    delimiter = ' ',
done

2024-02-07 16:08 UTC, merged