[RPA-1261] Collection folders view
runbotics/runbotics pull request #543
Opened 2024-02-01 11:33 UTC by seul88

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-02-01 13:24 UTC, preludium requested changes, later dismissed

2024-02-01 13:24 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/MenuItems/DeleteCollection.tsx
> +        console.log('Remove id=' + id);
leave a todo here

2024-02-01 13:24 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/MenuItems/EditCollection.tsx
> +        console.log(props);
leave todo

2024-02-01 13:24 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/MenuItems/MoveCollection.tsx
> +        console.log('Move id=' + id);
todo

2024-02-01 13:24 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionList.style.ts
> +export type Color = 'primary' | 'secondary' | 'error' | 'warning' | 'info' | 'success' | 'grey';
I assume that its copy-paste if so then use code that already there

2024-02-01 13:24 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.tsx
> +    const { id, name, isPublic } = {...props};
you dont need to create a copy of props in order to destructure it. imo destruct it in the function component params

2024-02-01 13:24 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.types.ts
copy-paste from Staś PR?

2024-02-01 13:35 UTC, seul88 commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.types.ts
yup, to replace after merge

2024-02-07 16:05 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.tsx
> +    const { id, name, isPublic } = {...props};
....ionTileProps> = ({ id, name, isPublic }) => {....

2024-02-08 13:31 UTC, Stanlee77 requested changes

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/MenuItems/EditCollection.tsx
> +        console.log(props);
after my PR merge to edit the collection you only need to use ProcessCollectionModifyDialog and pass param 'collection ' (collection that is being currently edited) to it

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/MenuItems/EditCollection.tsx
> +        console.log(props);
I'll handle it from the moment you add "three dots" with "edit" option
<img width="281" alt="image" src="https://github.com/runbotics/runbotics/assets/69820069/6d807076-cc01-4649-812b-c0f1e77af21c">

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionList.tsx
> +    const checkCollectionsWidth = (tagsWidthSum: number): void => {
tagsWidthSum - why tags?

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionList.tsx
> +        const collectionsWithGapsWidth: number = tagsWidthSum + (processCollections.length * 16);
create const PROCESS_COLLECTIONS_NUMBER = 16
is it always 16 even with different screen sizes?

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionList.tsx
> +        const collectionsWidthSum: number = handleWindowResize(refTags);
we prefer to avoid using assertions
useRef creates type slightly different than HTMLDivElement[]
<img width="251" alt="image" src="https://github.com/runbotics/runbotics/assets/69820069/e3022525-cc2f-4e64-8330-2782182fe7de">
same thing goes with Array.from(refCollectionBox.current.childNodes) 
<img width="217" alt="image" src="https://github.com/runbotics/runbotics/assets/69820069/69d81733-bba0-4608-a402-0c86f5b90550">
<img width="154" alt="image" src="https://github.com/runbotics/runbotics/assets/69820069/8aea5e34-6509-416b-ac56-7d52071879ec">

do you need HTMLDivElement[] type somewhere?

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionList.tsx
> +
remove newline

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionList.tsx
> +                <Grid ref={refCollectionBox} container xs={12} columnGap={2} rowGap={1}>
create const variables just like PROCESS_COLLECTIONS_NUMBER for the values (i suppose columnGap and/or rowGap) that decide if "expand" divider is shown

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.styles.ts
> +        padding: 2px 0 2px 20px;
use 
padding-left: 20px;
padding-block: 2px;
instead

2024-02-08 13:31 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.styles.ts
> +        padding: 2px 0 2px 20px;
1. better readiblilty
2. not overwriting value that is not used

2024-02-08 13:31 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.styles.ts
> +    <{ $isExpanded: boolean; }>(({ theme, $isExpanded }) => `
check the devtools - probably you'll get a warning saying you should use lowercase, for the props in elementary html elements

the solution is to e.g. change isExpanded -> expanded

2024-02-08 13:31 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.tsx
> +                        <Image src={PrivateIcon} alt='Private icon' />
translate text in alts

2024-02-08 13:31 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.tsx
> +                <Menu id="simple-menu" anchorEl={anchorEl} keepMounted open={!!anchorEl} onClose={handleClose}>
change id to more adequate name

2024-02-08 13:31 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessCollectionTile/ProcessCollectionTile.tsx
> +                <Menu id="simple-menu" anchorEl={anchorEl} keepMounted open={!!anchorEl} onClose={handleClose}>
should we keep it keep it mounted for sure? what's the use of it in our case?

2024-02-08 13:31 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/collections/general.ts
> +    'Process.Collection.List.CollapseLabel': 'collapse',
ExpandLabel -> Expand.Label
same for the collapse

2024-02-08 13:31 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/collections/general.ts
> +    'Process.Collection.List.CollapseLabel': 'zwiń',
just like in eng translations

2024-02-08 15:05 UTC, Stanlee77 approved these changes

2024-02-08 15:17 UTC, merged