[RPA-1302] Zip: unzip file
runbotics/runbotics pull request #556
Opened 2024-02-12 12:52 UTC by seul88

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-02-13 10:15 UTC, Stanlee77 approved these changes

2024-02-13 10:15 UTC, Stanlee77 commented on runbotics/runbotics-orchestrator-ui/src/src-app/Actions/zip.actions.ts
> +});
no tooltips?

2024-02-13 10:15 UTC, Stanlee77 commented
bump version

2024-02-13 10:36 UTC, preludium requested changes

2024-02-13 10:36 UTC, preludium commented on runbotics/runbotics-desktop/src/action/zip/zip.action-handler.ts
> +            const zip = new AdmZip(`${fullPath}.zip`);
if `path` is not provided you get `undefined` in fullPath

2024-02-13 10:36 UTC, preludium commented on runbotics/runbotics-desktop/src/action/zip/zip.types.ts
> +    path: string;
should be optional

2024-02-14 10:29 UTC, preludium approved these changes

2024-02-14 10:41 UTC, merged