[RPA-1338] Changed process search debounce
runbotics/runbotics pull request #587
Opened 2024-03-12 10:00 UTC by Aeri4a

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-03-12 10:12 UTC, preludium approved these changes

2024-03-12 11:03 UTC, stun-is-law requested changes

2024-03-12 11:03 UTC, stun-is-law commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useProcessSearch.ts
> +    const [searchField, setSearchField] = useState(searchFieldFromUrl || 'name');
if it's visible for user, than it should be translated
imo if it's searchField value than it should be empty, and there should be a placeholder in the inputs

2024-03-12 11:03 UTC, stun-is-law commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useProcessSearch.ts
> +const DEBOUNCE_TIME = 400;
have you tested if it works, e.g. by setting it to high value like 5000?

2024-03-13 09:14 UTC, stun-is-law approved these changes

2024-03-13 09:24 UTC, merged