[RPA-1307] BPMN error handling
runbotics/runbotics pull request #590
Opened 2024-03-14 10:33 UTC by seul88

## Description
**Demo process using error messages content to handle its flow is attached as .rbex file in JIRA ticket's details.**

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-03-14 10:49 UTC, preludium requested changes

2024-03-14 10:49 UTC, preludium commented on runbotics/runbotics-desktop/src/core/bpm/runtime/runtime.service.ts
> +                errorMessages: []
imo you don't need to initialize it at process startup

2024-03-14 10:49 UTC, preludium commented on runbotics/runbotics-desktop/src/core/websocket/bpmn/runtime-subscriptions.service.ts
> +                            processInstanceEvent.error = desktopTask.output.description;
use this function for it imo https://github.com/runbotics/runbotics/blob/99a3c68536872a7009c2f5918856775fa2be848a/runbotics/runbotics-desktop/src/core/bpm/runtime/runtime.service.ts#L642

2024-03-14 10:49 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useOptions.ts
> +    'errorMessages'
imo rename it to `caughtErrorMessage` we will store just the most recent error message

2024-03-22 12:45 UTC, preludium commented on runbotics/runbotics-desktop/src/action/variable/variable.action-handler.ts
> -        // assign to global scope
im not sure about it. debug what the difference between so called local and global scope

2024-03-27 13:40 UTC, stun-is-law approved these changes

2024-03-27 13:51 UTC, merged