[RPA-1281] Add action Folder: Exists
runbotics/runbotics pull request #597
Opened 2024-03-22 14:46 UTC by AdriannaSuchomska

## Description

Adds new folder action: Folder: Exists
![image](https://github.com/runbotics/runbotics/assets/92982209/c2d81d0b-a119-4442-b27d-fd8622360e81)

* folder name is a mandatory input
* if there is no path in the input data, the temp folder is assigned by default
* output: boolean

Development:
* adds function to check if the specified folder exists with verification of input data(name, path)
* adds tests for action Folder: Exists

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-03-25 21:23 UTC, marcin-depcik requested changes

2024-03-25 21:23 UTC, marcin-depcik commented on runbotics/runbotics-desktop/src/action/folder/folder.action-handler.ts
> +        const { name, path } = input;
You can destructure directly in function arguments.

2024-03-25 21:23 UTC, marcin-depcik commented on runbotics/runbotics-desktop/src/action/folder/folder.action-handler.ts
> +        }
Maybe it would be better to validate name and path first.

2024-03-25 21:23 UTC, marcin-depcik commented on runbotics/runbotics-desktop/src/action/folder/folder.action-handler.ts
> +    }
Delete empty line.

2024-03-27 08:59 UTC, preludium commented on runbotics/runbotics-desktop/src/action/folder/folder.action-handler.ts
> +            throw new Error('Cannot check if folder exists if name is not provided.');
make it simpler: `Name is not provided` that's all you need to tell to the user

2024-03-27 08:59 UTC, preludium commented on runbotics/runbotics-desktop/src/action/folder/folder.action-handler.ts
> +        if (path && !fs.existsSync(path)) {
```suggestion
        if (!path || !fs.existsSync(path)) {
```

2024-03-27 08:59 UTC, preludium commented on runbotics/runbotics-desktop/src/action/folder/folder.action-handler.ts
> +        if (path && !fs.existsSync(path)) {
`Path not provided or does not exist`

2024-03-27 11:36 UTC, AdriannaSuchomska commented on runbotics/runbotics-desktop/src/action/folder/folder.action-handler.ts
> +        if (path && !fs.existsSync(path)) {
Path is not required in this action.

2024-03-27 13:06 UTC, marcin-depcik approved these changes

2024-03-28 10:10 UTC, merged