[RPA-1260.4]  Show admin all collections in tree.
runbotics/runbotics pull request #607
Opened 2024-04-09 10:27 UTC by stun-is-law

…tions in tree & change runbotics user password.

## Description

## Motivation and Context

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-04-09 10:28 UTC, stun-is-law reviewed
self review

2024-04-09 10:52 UTC, marcin-depcik requested changes

2024-04-09 10:52 UTC, marcin-depcik commented on runbotics-orchestrator/src/main/java/com/runbotics/service/impl/ProcessCollectionServiceImpl.java
> +        }
you can remove `else` here

2024-04-09 10:52 UTC, marcin-depcik commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240409121600_changelog.xml
> +</databaseChangeLog>
I would add check if user with id 3 exists

2024-04-10 08:50 UTC, stun-is-law commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240409121600_changelog.xml
> +</databaseChangeLog>
okazuje sie, że preconditions można pozostawić puste - źródło [Preconditions (liquibase.com)](https://docs.liquibase.com/concepts/changelogs/preconditions.html)

2024-04-10 08:51 UTC, stun-is-law commented on runbotics-orchestrator/src/main/java/com/runbotics/service/impl/ProcessCollectionServiceImpl.java
> +        }
I could, ale czy mi się chce? xD

2024-04-10 09:44 UTC, merged