[RPA-1479] Tenants backend implementation
runbotics/runbotics pull request #614
Opened 2024-04-19 11:29 UTC by Aeri4a

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-04-22 09:18 UTC, stun-is-law requested changes
+ version bump

2024-04-22 09:18 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/service/UserService.java
> +        defaultTenant.setId(UUID.fromString("b7f9092f-5973-c781-08db-4d6e48f78e98"));
in lines 163-164 there's the same. Create function getDefaultTenant

2024-04-22 09:18 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/service/dto/TenantDTO.java
> +    }
what is it for?

2024-04-22 09:18 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/service/impl/GuestServiceImpl.java
> +        defaultTenant.setId(UUID.fromString("b7f9092f-5973-c781-08db-4d6e48f78e98"));
again -> use getDefaultTenant here

or even in class tenant assign default id and create a constructor that takes id as parameter - your choice

2024-04-22 09:18 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/web/rest/admin/TenantAdminResource.java
> +    }
what about checking the permissions? FKs

2024-04-22 09:18 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/java/com/runbotics/web/rest/tenant/TenantResource.java
> +}
add short comment above the commented code why is it left

2024-04-22 09:18 UTC, star-in-the-jar commented on runbotics/runbotics-common/src/model/api/authority.model.ts
> +    ROLE_TENANT_ADMIN = 'ROLE_TENANT_ADMIN',
can be left commented for now

2024-04-22 09:18 UTC, star-in-the-jar commented on runbotics/runbotics-common/src/model/api/feature-key.model.ts
> +    TENANT_EDIT = 'TENANT_EDIT',
what about TENANT_DELTE

2024-04-23 07:26 UTC, Aeri4a commented on runbotics-orchestrator/src/main/java/com/runbotics/service/dto/TenantDTO.java
> +    }
I think it isn't. My bad.

2024-04-24 08:33 UTC, stun-is-law approved these changes
+ version bump if it's not done yet

2024-04-24 08:33 UTC, stun-is-law commented on runbotics-orchestrator/src/main/java/com/runbotics/service/UserService.java
> +        newUser.setTenant(Utils.getDefaultTenant());
👍

2024-04-25 09:17 UTC, merged