[RPA-1512] Tenants frontend implementation
runbotics/runbotics pull request #628
Opened 2024-05-08 07:29 UTC by Aeri4a

## Description

![image](https://github.com/runbotics/runbotics/assets/80831299/9407f193-b9aa-4fb2-8f2b-8fd0e0e79ff1)

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-05-22 09:35 UTC, stun-is-law requested changes
bump version

2024-05-22 09:35 UTC, star-in-the-jar commented on runbotics/runbotics-common/src/model/api/tenant.model.ts
> +    lastModifiedBy?: string | null;
why can they be null and optional (?) parameter is not enough? Does it have anything to do with the DB?

2024-05-22 09:35 UTC, star-in-the-jar commented on runbotics/runbotics-common/src/model/api/tenant.model.ts
> +export type UserDTO = Pick<IUser, 'id' | 'login'>;
Is userDTO sth we send to backend to add/modify/delete user?

2024-05-22 09:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/hooks/useTenantSearch.ts
> +                    translate('Tenants.List.View.Events.Error.FindingTenants'),
instead 'FindingTenants' you can use ${ERROR_KEY} from backend response If you have more reasons the error could occur. If that's the only one there's no need.

2024-05-22 09:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/tenants/actions/modals.ts
> +    'Tenants.Actions.Modals.DeleteModal.Button.Cancel': 'Cancel',
for those let's use translations from common.json

2024-05-22 09:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/tenants/actions/modals.ts
> +    'Tenants.Actions.Modals.DeleteModal.Button.Cancel': 'Anuluj',
common.json again

2024-05-22 09:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/tenants/list/edit.ts
> +    'Tenants.List.Edit.Form.Button.Cancel': 'Anuluj',
common.json

2024-05-22 09:35 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/tenants/CreateTenantDialog.tsx
> +    const isFieldEmpty = !(name.trim() !== '');
does it work for sure?

2024-05-22 09:35 UTC, stun-is-law commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/tenants/DeleteTenantDialog.tsx
> +        <CustomDialog
cool, you've used that 😎

2024-05-22 09:35 UTC, stun-is-law commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/tenants/TenantsListView/TenantsListView.tsx
> +    };
Close/Create dialog is quite well described. "handle" keyword is not neccessary here - it well describes general actions

2024-05-22 09:35 UTC, stun-is-law commented on runbotics-orchestrator/src/main/java/com/runbotics/service/impl/TenantServiceImpl.java
> +                        () -> new BadRequestAlertException("Could not found user while updating", ENTITY_NAME, "userNotFound")
I haven't seen using "userNotFound" as translation key. Consider implementing this

2024-05-23 07:13 UTC, Aeri4a commented on runbotics/runbotics-common/src/model/api/tenant.model.ts
> +    lastModifiedBy?: string | null;
This is in order to use this interface to update Tenant inside user - so we don't need all fields

2024-05-23 07:27 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/tenants/CreateTenantDialog.tsx
> +    const isFieldEmpty = !(name.trim() !== '');
Yup, but I will remove unnecessary '!' and reverse logic.

2024-05-23 09:53 UTC, stun-is-law approved these changes

2024-05-23 09:55 UTC, merged