[RPA-1459] Password encryption
runbotics/runbotics pull request #641
Opened 2024-05-22 08:50 UTC by socjalis

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [+] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-05-23 10:17 UTC, stun-is-law requested changes
+ version bump

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +            </column>
Thoughful

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +            </column>
this should be not-null too, shouldn't it?

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +        <createTable tableName="process_context">
will this be updated with each update of process structure (xml)?

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +        <createTable tableName="process_context">
if so, and because the process has only one context why won't we add additional column in 'process' - "context"?

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +            <column name="order" type="int" />
why is that needed?

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +            <column name="order" type="int" />
does this value indicate which credential is used in the process? i.e. the smaller the value the earlier it is used in the process? does it apply to one process (i.e. always process has 1,2,3,4,5...) or is it general for all (i.e. process1 has 1,2,...,12; process2 has 13,14,...,21; and so on?

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +        <createTable tableName="process_context_secret">
what's this table for?

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/.env.development
> +ENCRYPTION_KEY='O3OTmXJpIIyUb3ByT4t65xblgsxfDGQu'
fyi

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/package.json
> +        "unplugin-swc": "~1.4.5"
sounds good, hope won't break anything

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/src/config/server-config/server-config.service.ts
> +    }
If someone gets access to:
1. this value through the .env or docker compose
2. database with iv's
can decrypt all passwords?

If so maybe it's worth to additionaly encrypt this value and pass decryption key when starting scheduler, just like we do with windows-bot? Also soon we should restrict access to server where the scheduler is running or runbotics-deployment gh repository to prevent from stealing the key by unauthorized person through break-in or phishing. 

I

2024-05-23 10:17 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/src/database/process-context/dto/decrypted-process-context.dto.ts
> +
what is the purpose of these newlines?

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/process-context/process-context.service.ts
> +// import * as util from 'util';
looks redundant

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/process-context/process-context.service.ts
> +        // ctxSecret.name = 'dupa';
top top secret

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/process-context/process-context.service.ts
> +                    data: this.secretService.decrypt(processSecret.secret),
so already decrypted secrets are passed to bot all at once just before running the process?

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/secret/create-secret.schema.ts
> +// just an example of zod usage
maybe leave TODO

is it for describing the requirements specification of the passwords? like special characters, length, etc?

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/secret/secret.entity.ts
> +}
considering this, leaving java behind is a good idea. neat

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/secret/secret.entity.ts
> +@Entity({ name: 'secret' })
'secrets' sound more appropriate than 'credentials' 👍

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/secret/secret.test.ts
> +                        find: vi.fn().mockResolvedValue([null]),
does it mean you're not creating salt here?

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/queue/processor/scheduler.processor.test.ts
> +const mock_ForceFailGuard: CanActivate = { canActivate: vi.fn(() => true) };
is it camel, Pascal or snake case? xD

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/queue/processor/scheduler.processor.test.ts
> +        schedulerProcessor = moduleRef.get(SchedulerProcessor); //todo: use it instead of constructor
is todo still needed?

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/queue/processor/scheduler.processor.test.ts
> +const mock_ForceFailGuard: CanActivate = { canActivate: vi.fn(() => true) };
don't quite get the message

2024-05-23 10:17 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/utils/pipes/zod-validation.pipe.ts
> +            console.log(error);
redundant now i guess

2024-05-23 13:10 UTC, marcin-depcik requested changes

2024-05-23 13:10 UTC, marcin-depcik commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +            <column name="name" type="text"/>
what this column is for?

2024-05-23 13:10 UTC, marcin-depcik commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +            <column name="order" type="int" />
not clear what this column is for?

2024-05-23 13:10 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/queue/process/process-input.service.test.ts
> +    orchestratorProcessInstanceId: 'dpa',
there is typo, you forgot about `u`

2024-05-23 13:10 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/database/tenant/tenant.entity.ts
> +    processContexts: ProcessContext[];
do we need `secrets` and `processContexts` if there is many-to-many relation with `processContextSecrets`?

2024-05-23 13:10 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/database/process/process.entity.ts
> +    context: ProcessContext | null;
I think, there is no column `context` in process table

2024-05-23 13:10 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/database/process-context/process-context.service.ts
> +                secretId: processSecret.secretId
why is it for if you also returning `secret` property which already has `id`

2024-05-23 14:08 UTC, marcin-depcik requested changes

2024-05-23 14:08 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/database/secret/secret.service.ts
> +        secret.iv = iv.toString('hex').slice(0, 16);
`iv.toString('hex').slice(0, 16)` should be assign to the variable

2024-05-29 10:24 UTC, stun-is-law approved these changes

2024-05-29 10:24 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +            </column>
lets add non-nullable

2024-05-29 10:24 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +        <createTable tableName="process_context_secret">
![image](https://github.com/runbotics/runbotics/assets/69820069/bd17e9f8-44b6-4d01-91fd-4d3c7b8d21f0) - me
![image](https://github.com/runbotics/runbotics/assets/69820069/5f8bd3ce-569f-4d46-9920-7846bbc93a76) - wiktor

2024-05-29 10:24 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +        <createTable tableName="process_context_secret">
benefits: modularity + easy implementation of new features (like encrypticng files)

2024-05-29 10:24 UTC, star-in-the-jar commented on runbotics-orchestrator/src/main/resources/config/liquibase/changelog/20240512127832_changelog.xml
> +            <column name="order" type="int" />
Let's use value 0 for default

2024-05-29 10:24 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/src/queue/processor/scheduler.processor.test.ts
> +const mock_ForceFailGuard: CanActivate = { canActivate: vi.fn(() => true) };
mockForceNoAuthWithOrchestrator

2024-05-29 10:24 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/src/database/process-context/process-context.service.ts
> +                secretId: processSecret.secretId
I know :p

2024-05-29 10:24 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/tenant/tenant.entity.ts
> +export class Tenant {
so what, now we have two tables with tenants?

2024-05-29 10:24 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/tenant/tenant.entity.ts
> +    lastModifiedBy: string;
this should be the same as created_by, shouldn't it?

2024-05-29 10:24 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/user/user.entity.ts
> +    tenants: Tenant[];
does it mean one user can have many tenants?

2024-05-29 10:24 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/migrations/1716903265350-Secrets.ts
> +    name = 'Secrets1716903265350'
why this name?

2024-05-29 10:24 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/scheduler-database/process-context/process-context.entity.ts
> +export class ProcessContext {
last modified date can be useful

2024-05-29 10:25 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/migrations/1716903265350-Secrets.ts
> +    name = 'Secrets1716903265350'
is it a template generated by  typeorm?

2024-05-29 10:31 UTC, marcin-depcik approved these changes

2024-05-29 12:11 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/scheduler-database/process-context/process-context.entity.ts
> +export class ProcessContext {
instead we should update process while updating processcontext table

2024-06-12 14:20 UTC, merged