Implement secrets manager backend.
runbotics/runbotics pull request #658
Opened 2024-06-25 06:23 UTC by stun-is-law

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-07-01 09:22 UTC, marcin-depcik requested changes

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-common/src/model/api/attribute.model.ts
I wonder if it makes sense to create these types in rb-common since they will be used only in rb-ui

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/database/authority/authority.entity.ts
> -        name: 'authority_feature_key',
why?

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.controller.spec.ts
This test doesn't check anything so I think it can be removed for now

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.entity.ts
> +    secret: Secret;
why we need `cascade: true` here?

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.module.ts
> +  imports: [TypeOrmModule.forFeature([Attribute]), TypeOrmModule.forFeature([Secret]), SecretModule],
you can pass multiple entities at once using forFeature `TypeOrmModule.forFeature([Attribute, Secret])`

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.spec.ts
another test to remove if not used

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.ts
> +    };
maybe it would be more type safe if you created the new empty secretEntity instance using secret repository and `.create` method, and then assigned following properties, and then save the entity?

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.ts
> +    };
same here but using attribute repository

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.ts
> +      // });
remove if not used

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.ts
> +    return attributes;
you can just return `this.attributeRepository.find({relations})` instead of awaiting

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.ts
> +    }
I am not suer if you always want to throw exception if attribute is not found, I wander if this case shouldn't be handled outside of the AttributeService

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.ts
> +    }
same here

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.ts
> +    // }
remove if not used

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.service.ts
> +    }
same here

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/credential-collection/credential-collection.controller.spec.ts
another test

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/credential-template/credential-template.entity.ts
> +    attributes: CredentialTemplateAttribute[];
I think, that if you would set here `cascade: true` you can save new credential template with attributes by just passing array of attributes to specific property for CredentialTemplate entity, you can test this, but it should resolve problem with using `Promise.all` inside

https://stackoverflow.com/questions/55098023/typeorm-cascade-option-cascade-ondelete-onupdate

2024-07-01 09:22 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/credential-template/credential-template.service.ts
> +      });
according to the above comment

2024-07-02 04:39 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/database/authority/authority.entity.ts
> -        name: 'authority_feature_key',
It was redundant and causing an error

2024-07-02 05:52 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.entity.ts
> +    secret: Secret;
I guess we don't. Wrongly, I've thought it's obligatory if I want to use onDelete: 'CASCADE'

2024-07-02 05:52 UTC, stun-is-law commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/attribute.entity.ts
> +    secret: Secret;
removed it

2024-07-02 06:41 UTC, stun-is-law commented on runbotics/runbotics-common/src/model/api/attribute.model.ts
It's already being used on scheduler (e.g. attribute.entity.ts or credential-template-attribute.entity.ts) and is going to be used on the UI probably (for fields validation). So in that case I think it makes sense

2024-07-08 09:57 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/dto/create-attribute.dto.ts
> +}).strict();
I think description is missing

2024-07-08 09:57 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/attribute/dto/update-attribute.dto.ts
> +});
same as in the create dto - description is missing

2024-07-08 09:57 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/dto/update-credential.dto.ts
> +});
we agreed that once credential is created general info (as name, description, template, collection) won't be updated, right?

2024-08-06 08:43 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/dto/create-credential.dto.ts
> +    name: z.string(),
what do you think about adding z.string().trim().min(1 or 3) and maybe max?

2024-08-06 08:47 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/dto/update-credential.dto.ts
> +>;
We agreed that there will be no option to update credential details once created. It can stay ofc for the future, but it won't be used atm.

2024-08-06 08:56 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/credential-attribute/credential-attribute.entity.ts
> +    tenantId: string;
Do we need it here? We have it in credential and CredentialAttributes[] sits there, so I think it will be enough?

2024-08-06 08:59 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/credential.service.ts
> +        await this.validateName(credentialDto.name, user.id);
what do you think about checking this after the if (!template)?

2024-08-06 09:05 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/credential.service.ts
> +  }
I am not sure - why we would need enpoint where there is not tenant check?
Also - for the consistence I would rename result to credential, but this is just a suggestion.

2024-08-06 11:41 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/credential.entity.ts
> +    collectionId: string;
won't it creeate a conflict?

2024-08-06 12:16 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/tenant/tenant.entity.ts
> +    credentials: Credential[];
Do we need it here? I think we can have only credentialCollections here, because attributes sits in credential and credentials sits in collection?

2024-08-06 13:28 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/credential.service.ts
> +  }
Should it check these 3 things? @Unique(['collectionId', 'name', 'tenantId'])

2024-08-06 21:55 UTC, marcin-depcik requested changes

2024-08-06 21:55 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/database/user/user.entity.ts
> +            credentialCollectionUser.userId,
you should have referred to `user`, not `usetId`.

2024-08-06 21:55 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/migrations/1722932873862-Credentials.ts
looks legit

2024-08-06 21:55 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/credential-collection-user/credential-collection-user.entity.ts
> +    @JoinColumn({ name: 'collection_id' })
is it even necessary here?

2024-08-06 21:55 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/credential-collection-user/credential-collection-user.entity.ts
> +    @JoinColumn({ name: 'user_id' })
same here, see docs example:
https://typeorm.io/many-to-many-relations#many-to-many-relations-with-custom-properties

I don't think that is necessary, maybe it messed up updating the collection?

2024-08-06 21:55 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/credential-collection/credential-collection.controller.ts
> +        this.logger.log('Created new credential collection with id: ' + collection.id);
maybe awaiting only because of logs is unnecessary here, my bad

2024-08-06 21:55 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/credential-collection/credential-collection.service.ts
> +        });
shouldn't you have used here:

await Promise.all(collectionUserArray.map((item) => {
            this.credentialCollectionUserRepository.remove(item);
        }))

2024-08-07 07:57 UTC, marcin-depcik approved these changes

2024-08-07 11:35 UTC, bhszewczyk approved these changes

2024-08-07 11:36 UTC, bhszewczyk commented
Good job @stun-is-law  @marcin-depcik

![image](https://github.com/user-attachments/assets/1bf2b2b8-8c0a-4e6a-be21-884f82221957)

2024-08-08 07:18 UTC, merged