[RPA-1622] Portainer in docker compose
runbotics/runbotics pull request #670
Opened 2024-07-23 07:41 UTC by Aeri4a

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-07-23 08:33 UTC, marcin-depcik requested changes

2024-07-23 08:33 UTC, marcin-depcik commented on runbotics/docker-compose.yml
> +      - 127.0.0.1:9000:9000
why do we need to expose this container outside dev PC?

2024-07-23 08:52 UTC, marcin-depcik commented on runbotics/docker-compose.yml
> +      - 127.0.0.1:9000:9000
nvm

2024-07-23 08:52 UTC, marcin-depcik approved these changes

2024-08-01 07:43 UTC, stun-is-law approved these changes

2024-08-01 08:19 UTC, merged