[RPA-1666] External actions scheduler migration
runbotics/runbotics pull request #700
Opened 2024-09-02 12:43 UTC by Aeri4a

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-09-03 10:18 UTC, star-in-the-jar approved these changes

2024-09-03 10:18 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/src/migrations/1725274222207-ActionFeatureKey.ts
> +    public async down(queryRunner: QueryRunner): Promise<void> {
is this one tested?

2024-09-03 10:18 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/src/scheduler-database/action/action.service.ts
> +            })).catch(() => {
.catch to new line

2024-09-03 10:18 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/src/scheduler-database/action/dto/create-action.dto.ts
> +    script: z.string().startsWith('external.').max(255),
You can add validation error message if conditions are not met - so user can be informed that action has to start with 'external.'

Example: 
![image](https://github.com/user-attachments/assets/52b06284-c207-4c61-9781-919eeb6f6315)

2024-09-03 10:18 UTC, star-in-the-jar commented on runbotics/runbotics-scheduler/src/scheduler-database/action/dto/update-action.dto.ts
> +    script: z.string().startsWith('external.').max(255),
same as above

2024-09-03 14:15 UTC, marcin-depcik requested changes

2024-09-03 14:15 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/action/action.entity.ts
> +    @PrimaryColumn({ type: 'varchar', length: 255 })
I think that `255` is a default length for type `varchar` in typeorm, isn't it?

2024-09-03 14:15 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/action/action.entity.ts
> +    @Column({ name: 'tenant_id', type: 'uuid', default: 'b7f9092f-5973-c781-08db-4d6e48f78e98' })
I would assign it to some kind of const variable accessible for project as `DEFAULT_TENENT_ID` or something like that

2024-09-03 14:15 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/action/action.entity.ts
> +    @ManyToOne(() => Tenant, tenant => tenant.id, { nullable: false })
`nullable: false` is also default value

2024-09-03 14:15 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/action/action.entity.ts
> +    @Column({ type: 'varchar', length: 255 })
additionally, typeorm by default maps `string` as `type: 'varchar', length: 255`

2024-09-03 14:15 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/action/dto/create-action.dto.ts
> +    script: z.string().startsWith('external.').max(255),
you can use `refine()` or message property 
![image](https://github.com/user-attachments/assets/f66ee8c4-81bf-4fa1-968f-b0b558bd9c62)

2024-09-06 11:47 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1725274222207-ActionFeatureKey.ts
> +    public async down(queryRunner: QueryRunner): Promise<void> {
yes, it is

2024-09-06 11:50 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/action/dto/create-action.dto.ts
> +    script: z.string().startsWith('external.').max(255),
Good idea!

2024-09-06 11:56 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/action/action.entity.ts
> +    @PrimaryColumn({ type: 'varchar', length: 255 })
Unfortunately, you are not right. I met this case before, if we delete it then typeorm migration generator will force to drop the whole column, which is not okay :/

2024-09-06 12:02 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/action/action.entity.ts
> +    @Column({ name: 'tenant_id', type: 'uuid', default: 'b7f9092f-5973-c781-08db-4d6e48f78e98' })
I will do it

2024-09-06 12:02 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/action/action.entity.ts
> +    @Column({ type: 'varchar', length: 255 })
That is not true. Probably the length is not set as fixed and that's why generator can see the difference. Those lengths are probably leftovers after Java.

2024-09-06 12:23 UTC, marcin-depcik approved these changes

2024-09-06 12:35 UTC, merged