[RPA-1694] Add page for error handling
runbotics/runbotics pull request #765
Opened 2024-10-04 13:53 UTC by AdriannaSuchomska

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-10-04 17:20 UTC, Aeri4a requested changes

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/pages/[code].tsx
There is little problem with this file, because of NextJS paging behaviour. If we go to site with url: '/404' it is fine, but everything we type which is not valid url like: '/abcd' will also work and display this component because it fits to everything, which is not good.

I am wondering if we could make it in those ways:
1. If there is known error then display it (like 404, 500 etc... ) -> I recommend use enum for known pages, and perhaps redirect if router.query is not valid or get default error type - 404? Those are just ideas, probably not perfect.
2. If there is custom error, we have a separate page like  for example '/error' ?
3. If we got on unknown site -> redirect to 404

---------------
Last thing - I would recommend and if you also think it is a good idea to move logic from pages to view and in pages create just a file with import/export like other files in this directory.

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/pages/[code].tsx
> +            sessionStorage.removeItem('errorMessage');
If you would continue this idea, you may try to do it with component unmount.

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/error404.json
Administrator or administrator, pick upper or lower case 😊

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/auth/RegisterPage/Register.page.tsx
> +                    router.push('/customerror');
I think 'error' would be clearer for users

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/auth/RegisterPage/Register.page.tsx
> +                    router.push('/customerror');
I know that for us *developers* it is well readable based on functionality, however this is url. You can share your opinion 😊

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/errors/ErrorView.tsx
> +};
I think you could move it to separate file.

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/errors/ErrorView.tsx
> +    const viewMessage = errorCode ? translate(`Error${errorCode}.View.Message` as any) : customMessage;
I don't know if casting to any it is a good idea. I don't remember how we make it work with translations, there should be somewhere an example of injecting value into that string.

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/errors/ErrorView.tsx
> +        : { bottom: '-5vw', maxBottom: '-5px' };
cool

2024-10-04 17:20 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/errors/ErrorView.tsx
> +    customMessage?: string;
shrink to message, title

2024-10-09 07:14 UTC, marcin-depcik approved these changes

2024-10-09 07:34 UTC, Aeri4a approved these changes

2024-10-21 08:00 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/errors/ErrorView.tsx
> +// import { RootState } from '#src-app/store';
Comment

2024-10-21 08:00 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/errors/ErrorView.tsx
>  const ErrorView: FC<ErrorViewProps> = () => {
You don't have to use empty interface, use just FC

2024-10-21 09:56 UTC, merged