[RPA-1654] Add modal with process details
runbotics/runbotics pull request #778
Opened 2024-10-14 14:15 UTC by marcin-depcik

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-10-15 07:40 UTC, bhszewczyk requested changes

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/components.json
> +    "Component.Tile.Process.Content.Updated.Placeholder": "Never",
I am not sure if in created "never" makes sense

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsDialog.tsx
> +                        {process?.name}
shouldn't process name be mandatory?

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/AccessTab.tsx
> +                {process?.processCollection?.users?.length ? (
process object should be mandatory here as well, right? + what do you think about extracting this to to variable

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/CredentialsTab.tsx
> +    const processId = process?.id;
also here - is there a reason process is optional?

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/CredentialsTab.tsx
> +        if (!processId) return;
how this can happen? :D maybe I am missing something, but if we are able to click on details there has to be a process

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/CredentialsTab.tsx
> +export const CredentialsTab = ({ value, process }: DetailsInfoTabProps) => {
this component has the same structure like the AccessTab component (same styling, but data is different - do you think it is possible to merge it into one component?

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/GeneralInfoTab.tsx
> +                {process?.tags?.length ? (
here also I would say that it should be process.tags?...

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/SchedulesTab.tsx
> +    const processId = process?.id;
same as above - I think in case there is no process this component should not be rendered

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/SchedulesTab.tsx
> +        : translate('Component.Tile.Process.Content.LastRun.Placeholder');
also - this does not make sense - above process can be undefined and here it cannot (there is no process?... optional chaining)

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/SchedulesTab.tsx
> +            .toLowerCase();
I love this function name <3

2024-10-15 07:40 UTC, bhszewczyk commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/SchedulesTab.tsx
> +        if (!processId) return;
same question as in other component - how it could even happen?

2024-10-15 07:41 UTC, bhszewczyk commented
+ there is something wrong with UI build

2024-10-15 09:15 UTC, star-in-the-jar approved these changes

2024-10-15 09:15 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/common.json
> +    "Common.Details": "Sczegóły",
missing 'z'

2024-10-15 09:15 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/AccessTab.tsx
> +                {process?.processCollection?.users?.length ? (
variable extraction is a good idea
plus it looks like a nice place for If condition component

2024-10-15 09:15 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/CredentialsTab.tsx
> +                )}
If component could be used here

2024-10-15 09:15 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/GeneralInfoTab.tsx
> +                )}
If component

2024-10-15 09:15 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/process/ProcessDetailsDialog/ProcessDetailsTabs/SchedulesTab.tsx
> +        ? moment(process.lastRun).fromNow()
moment is outdated, if possible use https://date-fns.org/ recently added by wiktor pilak

2024-10-22 13:33 UTC, bhszewczyk approved these changes

2024-10-22 16:04 UTC, merged