[RPA-1781] Tag functionality after process migration
runbotics/runbotics pull request #797
Opened 2024-11-08 15:19 UTC by marcin-depcik

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-11-08 15:56 UTC, Aeri4a requested changes

2024-11-08 15:56 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessTile/ProcessTileActions/ProcessTileActions.tsx
> +                                        // 'tags->name': search.trim(),
comments

2024-11-08 15:56 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessTile/ProcessTileActions/ProcessTileActions.tsx
> +                                        // 'tags->name': search.trim(),
It was originally like: createdByEmail OR tagName OR name

2024-11-08 15:56 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessTile/ProcessTileContent/ProcessTileContent.tsx
>                              matchingText={searchValue}
Why is highlighting not working?

2024-11-08 15:56 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessTile/ProcessTileTagList/ProcessTileTagList.tsx
> -                            />
why?

2024-11-08 15:56 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/process/dto/create-process.dto.ts
> +    executionInfo: z.string().trim().optional(),
can this be an empty string as you put in dispatch with updateExecutionInfo: '' ? or maybe a null value?

2024-11-08 15:56 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/process/process-crud.service.ts
> +// const RELATIONS: FindOptionsRelations<ProcessEntity> = {
comments

2024-11-14 08:05 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/process/process-crud.service.ts
> +const relations = ['tags', 'system', 'botCollection', 'output', 'createdBy', 'editor', 'processCollection.users'];
I think relations should be named with capitalized letters, like it was before

2024-11-14 08:06 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/process/process-crud.service.ts
> +            relations: relations,
relations: RELATIONS (if you decide that this variable name should be capitalized) or you can shorted this to just relations (no need for relations: relations)

2024-11-20 09:35 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessTile/ProcessTileActions/ProcessTileActions.tsx
> +                                        // 'tags->name': search.trim(),
done

2024-11-20 09:36 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/components/Tile/ProcessTile/ProcessTileContent/ProcessTileContent.tsx
>                              matchingText={searchValue}
done

2024-11-20 09:36 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/process/dto/create-process.dto.ts
> +    executionInfo: z.string().trim().optional(),
done

2024-11-20 10:43 UTC, bhszewczyk approved these changes

2024-11-20 10:43 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/scheduler-database/process/process-crud.service.ts
> +        );
you use this 3 times, so maybe it is worth extracting to the new private method where you just pass user. e.g.

```
private hasTenantAllAccess = (user) => { 
   return this.userService.hasFeatureKey(
            user,
            FeatureKey.TENANT_ALL_ACCESS
   )};
```
and then you can use it directly and not via additional variable. we would also avoid changing this couple of times in case in the future we change feature key

2024-11-20 11:28 UTC, merged