[RPA-1699.2] Full feature of credentials tab refactor and fixes
runbotics/runbotics pull request #806
Opened 2024-11-14 12:40 UTC by bhszewczyk

## Description

- Adds translations for templates
- Secures update and delete endpoints so the user with only READ access to collection cannot update/delete credential using API
- Fixes issue where relations wasn't properly retrieved which caused that table with users we share collection with was empty
- Refactors CreateGeneralInfoFormDialog component and extracts 2 components for better clarity and readability
-  Adds context for credentials paging

## Motivation and Context

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-11-18 08:19 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/credentials/Credential/CreateGeneralInfo/GeneralInfoSelectFields.tsx
> +        }
try not to use let, u can use in this case anonymous function and "call it in place" () => {}()

2024-11-18 08:19 UTC, Aeri4a commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/credentials/GridView/CredentialCollectionsGridView/CredentialCollectionsGridView.tsx
> +                collectionId={null}
Is it necessary to pass there null?

2024-11-18 08:19 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/credential.service.ts
> +    console.log('I go here');
console log :D

2024-11-20 08:35 UTC, marcin-depcik requested changes
bump version

2024-11-20 08:35 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/en/credenitals/credentials.ts
> +    'Credential.Template.MicrosoftGraph.Name': 'MicrosoftGraph',
I'd say it should be just `Microsoft`

2024-11-20 08:35 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/translations/pl/credenitals/credentials.ts
> +    'Credential.Template.MicrosoftGraph.Name': 'MicrosoftGraph',
same

2024-11-20 08:35 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/credentials/Credential/CreateGeneralInfo/CreateGeneralInfoFormDialog.tsx
> +            setFormValidationState(prevValues => ({...prevValues, edited: true}));
add spaces, please
`{ ...prevValues, edited: true }`

2024-11-20 08:35 UTC, marcin-depcik commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/credentials/GridView/Paging.provider.tsx
> +    // setPageSize: Dispatch<SetStateAction<number>>;
remove comment

2024-11-20 08:35 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/credential/credential.service.ts
> +    private throwExceptionIfUserHasReadAcces(collection: CredentialCollection, user: User) {
I'd rename it to something like `checkUserReadAccessOrThrow` because calling this function is a bit confusing

2024-11-20 12:21 UTC, marcin-depcik approved these changes

2024-11-22 09:51 UTC, star-in-the-jar approved these changes
+ version

2024-11-22 09:51 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/credentials/Credential/CreateGeneralInfo/CreateGeneralInfoFormDialog.tsx
> +                        />
noice

2024-11-22 09:51 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/credentials/Credential/CreateGeneralInfo/GeneralInfoSelectFields.tsx
> +    const availableCredentialCollections = credentialCollections?.filter(collection => collection.credentialCollectionUser.find(collectionUser => collectionUser.userId === currentUser.id && collectio
needs formatting

2024-11-22 09:51 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/credentials/Credential/CreateGeneralInfo/GeneralInfoSelectFields.tsx
> +    const availableCredentialCollections = credentialCollections?.filter(collection => collection.credentialCollectionUser.find(collectionUser => collectionUser.userId === currentUser.id && collectio
consider using useMemo for optymalization

2024-11-22 09:51 UTC, star-in-the-jar commented on runbotics/runbotics-orchestrator-ui/src/src-app/views/credentials/Credential/CreateGeneralInfo/GeneralInfoTextInputs.tsx
> +                    helperText={formValidationState.edited && !formValidationState.name && inputErrorMessages.NAME_IS_REQUIRED}
create variables for these booleans please

2024-11-22 11:19 UTC, merged