[RPA-552] Select element in browser widget
runbotics/runbotics pull request #83
Opened 2022-11-23 11:30 UTC by FranekMarciniak

2022-11-23 11:32 UTC, FranekMarciniak commented
TODO polskie translacje

2022-11-23 12:17 UTC, preludium requested changes

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/translations/en/process.json
> +    "Process.Details.Modeler.Actions.Browser.Target.LinkText.Tooltip": "Selects an link tag by its exact text (e.g. <strong>Click here</strong>)",
maybe change it to `Selects a link html element by its exact text`
and rewrite the below one also

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/translations/en/process.json
> +    "Process.Details.Modeler.Actions.Browser.Target.None.Tooltip": "This gives you the ability set prefix yourself (e.g. <strong>css=#my-id</strong>, <strong>xpath=//div[@id='my-id']</strong>)",
change it to `Allows to define selector type yourself`

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/translations/pl/process.json
> +    "Process.Details.Modeler.Actions.Browser.Target.CSS.Tooltip": "Selects an element by its CSS selector (e.g. <strong>input[name='username']</strong>, <strong>css=#my-id</strong>)",
these texts should be in polish

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +    const [formState, setFormState] = React.useState<BrowserTargetState>({prefix: '', value: ''});
move initial state to variable

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +        if(props.value){
spaces needed

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +const PREFIX_OPTIONS = {
move it to the component or create custom hook to use `useTranslations` hook

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +const FieldsWrapper = styled.div`
move everything but component to appropriate files like `.types`, `.utils`, `.styles`

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +        <InputLabel>Selector</InputLabel>
translation

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +    return <FieldsWrapper>
use parentheses

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +            {Object.keys(PREFIX_OPTIONS).map((option) => <MenuItem key={option} value={option}>{PREFIX_OPTIONS[option].label}</MenuItem>)}
move it to constant and brake it to multiple lines

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +    const onChangeWrapper = (prefix: string, value: string) => {
rename to `handleChangeWrapper` sounds like a prop

2022-11-23 12:17 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/views/process/ProcessBuildView/Modeler/ConfigureActionPanel/widgets/BrowserTargetWidget.tsx
> +            sx={{flexGrow: 1}}
spaces between curlies and content

2022-11-23 12:31 UTC, preludium commented on runbotics/runbotics-orchestrator-ui/src/translations/en/process.json
> +    "Process.Details.Modeler.Actions.Browser.Target.None.Tooltip": "This gives you the ability set prefix yourself (e.g. <strong>css=#my-id</strong>, <strong>xpath=//div[@id='my-id']</strong>)",
maybe it's worth to list all possible selectors?

2022-11-28 12:08 UTC, preludium approved these changes

2022-11-28 12:14 UTC, merged