[RPA-1642] Add CASCADE to related resources
runbotics/runbotics pull request #841
Opened 2024-12-11 09:08 UTC by marcin-depcik

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-12-12 08:17 UTC, Aeri4a requested changes
Just a few comments in order to mark specific places in code

2024-12-12 08:17 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/database/process-collection/process-collection.entity.ts
>      @JoinColumn({ name: 'parent_id' })
If we want to drop the whole hierarchy of collections then it could be like this.

2024-12-12 08:17 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/bot-collection/bot-collection.entity.ts
> +    )
I thought that we decided that unless we won't have resources migrations from one user to another. Then we won't cascade resources related to deleted user

2024-12-12 08:17 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/bot/bot.entity.ts
> +    )
user here

2024-12-12 08:17 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/scheduler-database/process/process.entity.ts
> +    )
I think as long as we don't have an endpoint to delete process output - it is safe to do it. Otherwise, I wouldn't think so.

2024-12-12 08:17 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "process" ALTER COLUMN "updated" DROP DEFAULT`);
Do you know why it is removing default here?

2024-12-12 08:17 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "bot" ADD CONSTRAINT "FK_a3190460df612af6ab214b44a92" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
The one I think we don't want

2024-12-12 08:17 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "bot_collection" ADD CONSTRAINT "FK_259ea10c3617e2c3564d0ead503" FOREIGN KEY ("created_by") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE NO ACT
Also user

2024-12-12 08:17 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "process_collection" ADD CONSTRAINT "FK_3c30da520c249192c358cf4beb3" FOREIGN KEY ("parent_id") REFERENCES "process_collection"("id") ON DELETE CASCADE ON
This one I am not sure

2024-12-12 08:21 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "process" ALTER COLUMN "updated" DROP DEFAULT`);
column - "updated" in process

2024-12-12 08:21 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "bot" ADD CONSTRAINT "FK_a3190460df612af6ab214b44a92" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
(last line) - bot

2024-12-12 08:21 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "bot_collection" ADD CONSTRAINT "FK_259ea10c3617e2c3564d0ead503" FOREIGN KEY ("created_by") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE NO ACT
(last line)

2024-12-12 08:21 UTC, Aeri4a commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "process_collection" ADD CONSTRAINT "FK_3c30da520c249192c358cf4beb3" FOREIGN KEY ("parent_id") REFERENCES "process_collection"("id") ON DELETE CASCADE ON
(also last line)

2024-12-12 08:49 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/bot-collection/bot-collection.entity.ts
> +    )
I decided to do this only for less important resources, after all, we would have done it anyway

2024-12-12 09:00 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/process/process.entity.ts
> +    )
this is onUpdate strategy

2024-12-12 16:00 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "process" ALTER COLUMN "updated" DROP DEFAULT`);
This is intentional and follows from previous changes, there are cases where we do not want the process update date to be modified automatically, like for example update of `last_run` column

2024-12-12 16:08 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "process_collection" ADD CONSTRAINT "FK_3c30da520c249192c358cf4beb3" FOREIGN KEY ("parent_id") REFERENCES "process_collection"("id") ON DELETE CASCADE ON
At the moment, when a users uses the UI and wants to delete the entire process collection with content, they get a message that they will delete everything in the collection, but despite this information they get an error from the backend. I think this needs to be standardised

2024-12-13 10:25 UTC, bhszewczyk commented on runbotics/runbotics-scheduler/src/migrations/1733843426128-Cascade.ts
> +        await queryRunner.query(`ALTER TABLE "process_collection" ADD CONSTRAINT "FK_3c30da520c249192c358cf4beb3" FOREIGN KEY ("parent_id") REFERENCES "process_collection"("id") ON DELETE CASCADE ON
Agree - on UI there is this information on collection deletion that everything what is inside this collection will be removed. So if we want this to work it is ok to do that.

2024-12-13 10:56 UTC, bhszewczyk approved these changes

2024-12-13 12:17 UTC, marcin-depcik commented on runbotics/runbotics-scheduler/src/scheduler-database/bot-collection/bot-collection.entity.ts
> +    )
I created task for this

2024-12-13 13:03 UTC, merged