[RPA-1890] Change api/processes to scheduler
runbotics/runbotics pull request #847
Opened 2024-12-12 12:18 UTC by Aeri4a

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

2024-12-12 16:42 UTC, marcin-depcik approved these changes

2024-12-12 16:42 UTC, marcin-depcik commented on runbotics/runbotics-desktop/src/action/general/general.action-handler.ts
> +        private readonly storageService: StorageService,
I think you need to import ConfigModule inside CoreModule

2024-12-12 16:42 UTC, marcin-depcik commented on runbotics/runbotics-desktop/src/action/general/general.action-handler.ts
> +        const tenantId = this.storageService.getValue('tenantId');
I know that, we have such implementation, but I don't think this is a good approach of keeping such information like `tenantId`. Maybe we should think about changing it in the future

2024-12-12 16:42 UTC, marcin-depcik reviewed
bump version

2024-12-13 10:38 UTC, star-in-the-jar requested changes
+version

2024-12-13 10:38 UTC, star-in-the-jar commented on runbotics/runbotics-desktop/src/action/general/general.action-handler.ts
> +        const tenantId = this.storageService.getValue('tenantId');
Good point, if it's stored in local storage there's a risk someone can exploit that to access resources of another tenant

2024-12-13 10:38 UTC, star-in-the-jar commented on runbotics/runbotics-desktop/src/core/websocket/listeners/process.listener.ts
> +            const tenantId = this.storageService.getValue('tenantId');
If there's a risk of overwriting this value by a user, we need a bugfix task in #tobediscussed

2024-12-13 15:24 UTC, marcin-depcik commented on runbotics/runbotics-desktop/src/core/websocket/listeners/process.listener.ts
> +            const tenantId = this.storageService.getValue('tenantId');
I created task for this

2024-12-16 08:13 UTC, merged